import fs from 'node:fs/promises';
import path from 'node:path';
const root = path.resolve('output/image-search-spike');
const dataset = JSON.parse(await fs.readFile(path.join(root, 'dataset.json'), 'utf8'));
const models = [];
for (const slug of ['clip-vit-base-patch32', 'clip-vit-base-patch16', 'voyage-multimodal-3.5']) {
  try { models.push(JSON.parse(await fs.readFile(path.join(root, slug, 'results.json'), 'utf8'))); } catch {}
}
if (!models.length) throw new Error('No benchmark results');
const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const payload = JSON.stringify({ models, products: dataset.products.map(p => ({ id: p.id, sku: p.sku, name: p.name, category: p.category })) }).replace(/</g, '\\u003c');
const cards = models.map(model => {
  const holdout = model.summary.metrics.filter(m => m.split === 'holdout');
  const hosted = model.summary.hostedQueryMs;
  const timing = hosted ?? model.summary.warmLocalQueryMs;
  return `<article><h3>${escape(model.summary.modelId.split('/')[1])}</h3>${holdout.map(m => `<p>${m.kind === 'compressed' ? 'ภาพย่อ: พบใน 5 อันดับแรก' : 'ภาพอีกไฟล์: พบชิ้นเดิมใน 10 อันดับแรก'} <strong>${m.kind === 'compressed' ? m.hit5 : m.hit10}/${m.total}</strong></p>`).join('')}<p>${hosted ? 'เวลาเรียกบริการ AI รวมเครือข่าย' : 'เวลาค้นหาบนเครื่อง'} p95 <strong>${(timing.p95 / 1000).toFixed(2)} วินาที</strong></p>${hosted ? `<p>ค่าทดลองที่ API รายงาน <strong>$${model.summary.reportedCostUsd.toFixed(4)}</strong></p>` : ''}</article>`;
}).join('');
const html = `<!doctype html><html lang="th"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GISP — ทดลองค้นหาด้วยภาพ</title>
<style>body{font-family:Tahoma,Arial,sans-serif;margin:0;color:#23382e;background:#f5f4ef;line-height:1.65}main{max-width:1250px;margin:auto;padding:30px}h1{font-size:32px;margin-bottom:5px}h2{font-size:23px}.muted{color:#69766e}.banner{background:#e7efe9;padding:18px;border-radius:12px}.summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px}article{background:#fff;border:1px solid #dfe3dc;border-radius:12px;padding:18px}.controls{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:20px 0}select,button{font:inherit;padding:10px;border:1px solid #b9c6bb;border-radius:8px;background:white}button{cursor:pointer}.source{display:flex;gap:20px;align-items:center}.source img{width:210px;height:185px;object-fit:contain;background:#fff;border-radius:10px}.matches{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;margin-top:16px}.matches img{width:100%;height:140px;object-fit:contain}.matches article{padding:12px}.matches p{font-size:12px;margin:4px 0}.matches select{font-size:12px;width:100%;padding:5px}.tag{font-size:12px;background:#edf0eb;border-radius:20px;padding:4px 10px}.status{min-height:24px}#case{scroll-margin-top:20px}footer{margin-top:35px;color:#657267;font-size:13px}@media(max-width:600px){main{padding:16px}h1{font-size:26px}.source{display:block}.source img{width:100%}.matches{grid-template-columns:repeat(2,minmax(0,1fr))}}</style>
<main><div class="tag">GISP · ขั้นตอนที่ 1 · ผลเปรียบเทียบ AI</div><h1>ค้นหาสินค้าด้วยภาพ</h1><p class="muted">${dataset.summary.eligibleProducts} สินค้า · ${dataset.summary.categories.length} หมวด · ตัวอย่าง ${dataset.summary.sampleProducts} สินค้า · ยังไม่ได้เปิดใช้ในระบบจริง</p>
<div class="banner">ผลนี้วัดการค้นหาสินค้าชิ้นเดิมจากภาพย่อและภาพอีกไฟล์ใน Catalog ยังไม่ใช่คะแนนความแม่นยำจากภาพถ่ายของลูกค้า และยังไม่ผ่านการตัดสินว่าสินค้าต่างชิ้นคล้ายพอหรือไม่</div>
<h2>ผลชุดที่แยกไว้ทดสอบ</h2><div class="summary">${cards}</div><p class="muted">เวลาของ CLIP วัดบนเครื่อง ส่วน Voyage รวมเครือข่ายไปบริการ AI จึงเทียบความเร็วโดยตรงไม่ได้ ทุกแบบยังไม่รวมการอัปโหลดจากผู้ใช้และฐานข้อมูลจริง ผลลัพธ์ด้านล่างยังไม่มีเกณฑ์ตัดสินว่า “ไม่พบ”</p>
<h2>ตรวจภาพและสินค้าที่ค้นเจอ</h2><p>เลือกตัวอย่างแล้วเทียบรูปกับผลค้นหา ให้คะแนนเฉพาะรายการที่ตรวจแล้ว ปุ่มบันทึกจะดาวน์โหลดไฟล์ผลตรวจลงเครื่อง ไม่มีการส่งข้อมูลออกจากหน้านี้</p>
<div class="controls"><label>โมเดล <select id="model"></select></label><label>ชุดภาพ <select id="kind"><option value="alternate-proxy">ภาพอีกไฟล์ใน Catalog</option><option value="compressed">ภาพย่อ/บีบอัด</option></select></label><button id="prev">ก่อนหน้า</button><button id="next">ถัดไป</button><span id="counter"></span><button id="save">บันทึกผลตรวจ</button></div>
<div id="case"></div><p class="status" id="status" aria-live="polite"></p><footer>คะแนนที่บันทึกเป็นความเห็นของผู้ตรวจ ไม่เปลี่ยนผล benchmark อัตโนมัติ ต้องรวบรวมภาพถ่ายจริงและภาพที่ไม่มีสินค้าคล้ายเพิ่มก่อนรับรองคุณภาพ</footer></main>
<script>const data=${payload};let index=0;const ratings={};const model=document.getElementById('model');data.models.forEach((m,i)=>{const o=document.createElement('option');o.value=i;o.textContent=m.summary.modelId.split('/')[1];model.append(o)});const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function current(){return data.models[Number(model.value)].queries.filter(q=>q.kind===document.getElementById('kind').value)}function render(){const list=current();if(!list.length){document.getElementById('case').textContent='ไม่มีภาพชุดนี้';return}index=(index+list.length)%list.length;const q=list[index];const p=data.products.find(p=>p.id===q.productId);document.getElementById('counter').textContent=(index+1)+' / '+list.length;document.getElementById('case').innerHTML='<article><div class="source"><img src="'+esc(q.relative)+'" alt="ภาพค้นหา"><div><span class="tag">'+esc(q.split)+'</span><h3>'+esc(p.name)+'</h3><p>'+esc(p.sku)+' · '+esc(p.category)+'</p><p>พบสินค้าชิ้นเดิมอันดับที่ '+q.expectedRank+'</p><p class="muted">ภาพอีกไฟล์อาจเป็นภาพรายละเอียดหรือมีข้อความ ต้องตรวจว่าเห็นสินค้าเพียงพอ</p></div></div><div class="matches">'+q.top10.map((p,i)=>'<article><img src="'+esc(p.relative)+'" alt="'+esc(p.name)+'"><p><strong>'+(i+1)+'. '+esc(p.sku)+'</strong></p><p>'+esc(p.name)+'</p><select data-product="'+p.productId+'" aria-label="ให้คะแนนผล '+(i+1)+'"><option value="">ยังไม่ได้ตรวจ</option><option value="same">ชิ้นเดิม</option><option value="similar">คล้าย ยอมรับได้</option><option value="different">ไม่คล้าย</option><option value="unclear">ภาพไม่ชัด ตัดสินไม่ได้</option></select></article>').join('')+'</div></article>';document.querySelectorAll('[data-product]').forEach(s=>{const key=data.models[Number(model.value)].summary.modelId+'|'+q.id+'|'+s.dataset.product;s.value=ratings[key]??'';s.onchange=()=>{if(s.value)ratings[key]=s.value;else delete ratings[key];document.getElementById('status').textContent='ตรวจแล้ว '+Object.keys(ratings).length+' คู่ภาพ (กดบันทึกก่อนปิดหน้า)'}})}model.onchange=()=>{index=0;render()};document.getElementById('kind').onchange=()=>{index=0;render()};document.getElementById('prev').onclick=()=>{index--;render()};document.getElementById('next').onclick=()=>{index++;render()};document.getElementById('save').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify({reviewedAt:new Date().toISOString(),purpose:'exploratory-human-review',ratings},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='gisp-image-search-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};render();</script></html>`;
await fs.writeFile(path.join(root, 'review.html'), html);
const imageCapPixels = 768 * 768;
const perImageUpperUsd = imageCapPixels * .60 / 1_000_000_000;
const hostedSummary = models.find(m => m.summary.modelId === 'voyageai/voyage-multimodal-3.5')?.summary;
const costs = {
  checkedAt: new Date().toISOString(), currency: 'USD', providerBenchmarkRun: Boolean(hostedSummary),
  hostedExperiment: hostedSummary ? { gateway: 'OpenRouter', reportedCostUsd: hostedSummary.reportedCostUsd, missingCostResponses: hostedSummary.missingCostResponses, conservativeReservedUsd: hostedSummary.conservativeReservedUsd, pricingSource: 'https://openrouter.ai/voyageai/voyage-multimodal-3.5' } : null,
  source: 'https://docs.voyageai.com/docs/pricing', provider: 'voyage-multimodal-3.5 direct API',
  assumptions: ['Maximum 768x768 pixels, no text, before free credits, taxes, storage, network and worker cost', 'No API account or payment method provisioned'],
  perImageUpperUsd, catalogFull3568UpperUsd: dataset.summary.eligibleImageRecords * perImageUpperUsd,
  catalogPrimary634UpperUsd: dataset.summary.eligibleProducts * perImageUpperUsd,
  queryMonthlyExamples: [1000, 10000, 100000].map(count => ({ count, upperUsd: count * perImageUpperUsd })),
  cpuHostingIllustration: { source: 'https://huggingface.co/docs/inference-endpoints/pricing', type: 'AWS intel-spr x2, 2 vCPU / 4GB', hourlyUsd: .067, hours: 730, monthlyUsd: .067 * 730, validatedOnThisHost: false },
  localInferenceProviderChargeUsd: 0,
};
await fs.writeFile(path.join(root, 'costs.json'), JSON.stringify(costs, null, 2));
console.log(JSON.stringify({ review: path.join(root, 'review.html'), costs }, null, 2));
