import { NextResponse,type NextRequest } from "next/server";
import { apiError,invalidInput } from "@/lib/api/response";
import { updateProjectSchema } from "@/lib/projects/schema";
import { AppAccessError,requireAppAccess } from "@/lib/auth/session";
import { createInsForgeServerClient } from "@/lib/insforge/server";
export async function GET(_request:NextRequest,{params}:{params:Promise<{id:string}>}){try{const context=await requireAppAccess({active:true});if(!context.roles.includes("MEMBER"))throw new AppAccessError("PERMISSION_DENIED",403,"หน้านี้สำหรับสมาชิก");const {id}=await params;const db=await createInsForgeServerClient();const projectResult=await db.database.from("projects").select("id,project_number,name,project_type,site_address,status,expected_need_date,note,end_customer_id,created_at,updated_at").eq("id",id).maybeSingle();if(projectResult.error)throw projectResult.error;if(!projectResult.data)return NextResponse.json({message:"ไม่พบโครงการ"},{status:404});const customerPromise=projectResult.data.end_customer_id
 ? db.database.from("end_customers").select("id,name,phone,email,address,note").eq("id",projectResult.data.end_customer_id).maybeSingle()
 : Promise.resolve({data:null,error:null});const [customer,areas,items,visits,disclosures]=await Promise.all([
 customerPromise,
 db.database.from("project_areas").select("id,name,note,sort_order").eq("project_id",id).order("sort_order").limit(100),
 db.database.from("project_items").select("id,area_id,product_id,variant_id,item_type,item_name,product_sku_snapshot,category_name_snapshot,specification_snapshot,selected_options,quantity,unit,current_unit_price,suggested_resale_amount,freight_estimate_min,freight_estimate_max,lead_time_days_snapshot,vat_rate_snapshot,status,ordered_quantity,created_at,updated_at").eq("project_id",id).order("created_at").limit(500),
 db.database.rpc("get_member_showroom_visits",{project_id_input:id}),
 db.database.rpc("get_member_project_disclosures",{project_id_input:id})
]);for(const result of [customer,areas,items,visits,disclosures])if(result.error)throw result.error;return NextResponse.json({data:{project:projectResult.data,customer:customer.data,areas:areas.data??[],items:items.data??[],visits:visits.data??[],disclosures:disclosures.data??[]}})}catch(error){return apiError(error)}}
export async function PATCH(request:NextRequest,{params}:{params:Promise<{id:string}>}){try{const context=await requireAppAccess({active:true});if(!context.roles.includes("MEMBER"))throw new AppAccessError("PERMISSION_DENIED",403,"หน้านี้สำหรับสมาชิก");const parsed=updateProjectSchema.safeParse(await request.json());if(!parsed.success)return invalidInput(parsed.error.flatten().fieldErrors);const {id}=await params;const input=parsed.data;const db=await createInsForgeServerClient();const {data,error}=await db.database.rpc("update_project_v2",{project_id_input:id,name_input:input.name,project_type_input:input.projectType,end_customer_name_input:input.endCustomerName,end_customer_phone_input:input.endCustomerPhone,end_customer_email_input:input.endCustomerEmail,site_address_input:input.siteAddress,expected_need_date_input:input.expectedNeedDate||null,note_input:input.note});if(error)throw error;return NextResponse.json({data,message:"แก้ไขโครงการเรียบร้อยแล้ว"})}catch(error){return apiError(error)}}
