import { calculateMoney } from "../lib/money";
import type {
  DemoClaim,
  DemoCustomRequest,
  DemoDocument,
  DemoOrganization,
  DemoOrder,
  DemoPaymentSchedule,
  DemoPaymentTransfer,
  DemoProduct,
  DemoProductionEvent,
  DemoProject,
  DemoProjectItem,
  DemoQcInspection,
  DemoQuotation,
  DemoShipment,
  DemoSupplier,
  DemoSupplierOrder,
  DemoUser,
} from "./types";

export const DEMO_PROJECT_NAME = "Riverstone Boutique Hotel Bangkok";
export const DEMO_MEMBER_COMPANY = "Atelier Nara Design Co., Ltd.";

export const demoOrganizations = [
  {
    id: "org-gisp",
    code: "GISP",
    name: "Global Interior Supply Platform",
    kind: "GISP",
  },
  {
    id: "org-member-atelier-nara",
    code: "MEM-0001",
    name: DEMO_MEMBER_COMPANY,
    kind: "MEMBER",
  },
  {
    id: "org-customer-riverstone",
    code: "CUS-0001",
    name: "Siam Riverstone Hospitality Co., Ltd.",
    kind: "END_CUSTOMER",
  },
] satisfies DemoOrganization[];

export const demoUsers = [
  {
    id: "user-member-nara",
    organizationId: "org-member-atelier-nara",
    fullName: "นารา วัฒนศิลป์",
    role: "MEMBER",
    title: "Interior Design Director",
  },
  {
    id: "user-gisp-admin",
    organizationId: "org-gisp",
    fullName: "กิตติพงษ์ จัดซื้อ",
    role: "GISP_ADMIN",
    title: "Order & Product Admin",
  },
  {
    id: "user-finance",
    organizationId: "org-gisp",
    fullName: "พิมพ์ชนก การเงิน",
    role: "FINANCE",
    title: "Finance Officer",
  },
  {
    id: "user-qc",
    organizationId: "org-gisp",
    fullName: "ธนกฤต ตรวจสินค้า",
    role: "QC",
    title: "QC Inspector",
  },
  {
    id: "user-logistics",
    organizationId: "org-gisp",
    fullName: "ศิรินทร์ โลจิสติกส์",
    role: "LOGISTICS",
    title: "Logistics Coordinator",
  },
  {
    id: "user-executive",
    organizationId: "org-gisp",
    fullName: "GISP Executive",
    role: "EXECUTIVE",
    title: "Executive Viewer",
  },
] satisfies DemoUser[];

export const demoSuppliers = [
  {
    id: "supplier-foshan-seating",
    code: "SUP-CN-001",
    name: "Foshan Demo Seating Works",
    city: "Foshan",
    country: "China",
    internalNote: "โรงงานเก้าอี้หลัก เงื่อนไขชำระ 50/50",
  },
  {
    id: "supplier-zhongshan-living",
    code: "SUP-CN-002",
    name: "Zhongshan Demo Living",
    city: "Zhongshan",
    country: "China",
    internalNote: "โรงงานโต๊ะและโคมไฟ มีประวัติล่าช้าเฉลี่ย 3–5 วัน",
  },
  {
    id: "supplier-guangzhou-bespoke",
    code: "SUP-CN-003",
    name: "Guangzhou Demo Bespoke",
    city: "Guangzhou",
    country: "China",
    internalNote: "โรงงาน Custom ต้องยืนยันตัวอย่างสีทุกครั้งก่อน Dispatch",
  },
] satisfies DemoSupplier[];

export const demoCatalog = [
  {
    id: "product-lounge-chair",
    sku: "CHR-LNG-001",
    nameTh: "เก้าอี้เลานจ์",
    nameEn: "Lounge Chair",
    kind: "STANDARD",
    supplierId: "supplier-foshan-seating",
    category: "Seating",
    memberUnitPrice: "18500.00",
    factoryUnitCost: "11000.00",
    currency: "THB",
    leadTimeDays: 45,
    specification: "ผ้าบุสี Sand Beige, ขาโลหะพ่นสี Bronze",
  },
  {
    id: "product-side-table",
    sku: "TBL-SID-002",
    nameTh: "โต๊ะข้าง",
    nameEn: "Side Table",
    kind: "STANDARD",
    supplierId: "supplier-zhongshan-living",
    category: "Table",
    memberUnitPrice: "6200.00",
    factoryUnitCost: "3800.00",
    currency: "THB",
    leadTimeDays: 40,
    specification: "ท็อปหินสังเคราะห์สี Ivory, โครงสี Antique Brass",
  },
  {
    id: "product-dining-chair",
    sku: "CHR-DIN-014",
    nameTh: "เก้าอี้รับประทานอาหาร",
    nameEn: "Dining Chair",
    kind: "STANDARD",
    supplierId: "supplier-foshan-seating",
    category: "Seating",
    memberUnitPrice: "7900.00",
    factoryUnitCost: "4600.00",
    currency: "THB",
    leadTimeDays: 45,
    specification: "โครงไม้สี Walnut, เบาะผ้าสี Olive",
  },
  {
    id: "product-pendant-light",
    sku: "LGT-PEN-009",
    nameTh: "โคมไฟแขวน",
    nameEn: "Pendant Light",
    kind: "STANDARD",
    supplierId: "supplier-zhongshan-living",
    category: "Lighting",
    memberUnitPrice: "9800.00",
    factoryUnitCost: "5500.00",
    currency: "THB",
    leadTimeDays: 40,
    specification: "แก้วฝ้าสี Opal, โลหะสี Brushed Brass",
  },
  {
    id: "product-reception-counter",
    sku: "CUS-REC-001",
    nameTh: "เคาน์เตอร์ต้อนรับสั่งผลิต",
    nameEn: "Custom Reception Counter",
    kind: "CUSTOM",
    supplierId: "supplier-guangzhou-bespoke",
    category: "Built-in",
    memberUnitPrice: "165000.00",
    factoryUnitCost: "95000.00",
    currency: "THB",
    leadTimeDays: 60,
    specification: "วีเนียร์ Walnut, ท็อปหิน, Cable Management และไฟ LED",
  },
  {
    id: "product-upholstered-headboard",
    sku: "CUS-HDB-010",
    nameTh: "หัวเตียงบุผ้าสั่งผลิต",
    nameEn: "Custom Upholstered Headboard",
    kind: "CUSTOM",
    supplierId: "supplier-guangzhou-bespoke",
    category: "Guest Room",
    memberUnitPrice: "22500.00",
    factoryUnitCost: "12500.00",
    currency: "THB",
    leadTimeDays: 60,
    specification: "กว้าง 2200 มม. ผ้าสี Terracotta พร้อมไฟอ่านหนังสือ",
  },
] satisfies DemoProduct[];

export const demoProject = {
  id: "project-riverstone",
  code: "PRJ-2026-000001",
  organizationId: "org-member-atelier-nara",
  endCustomerOrganizationId: "org-customer-riverstone",
  name: DEMO_PROJECT_NAME,
  projectType: "BOUTIQUE_HOTEL",
  siteAddress: "ถนนเจริญกรุง กรุงเทพมหานคร (ที่อยู่สมมติสำหรับ Demo)",
  areas: ["Lobby", "Guest Rooms", "All-day Dining"],
  targetDeliveryDate: "2026-11-30",
  status: "ACTIVE",
} satisfies DemoProject;

export const demoStandardProjectItems = [
  {
    id: "item-lounge-chair",
    projectId: demoProject.id,
    productId: "product-lounge-chair",
    supplierId: "supplier-foshan-seating",
    area: "Lobby",
    quantity: 8,
    kind: "STANDARD",
    memberUnitPriceSnapshot: "18500.00",
    specificationSnapshot: "ผ้าบุสี Sand Beige, ขาโลหะพ่นสี Bronze",
    status: "READY_TO_ORDER",
    customQuotationId: null,
    memberApprovedAt: null,
  },
  {
    id: "item-side-table",
    projectId: demoProject.id,
    productId: "product-side-table",
    supplierId: "supplier-zhongshan-living",
    area: "Lobby",
    quantity: 12,
    kind: "STANDARD",
    memberUnitPriceSnapshot: "6200.00",
    specificationSnapshot: "ท็อปสี Ivory, โครงสี Antique Brass",
    status: "READY_TO_ORDER",
    customQuotationId: null,
    memberApprovedAt: null,
  },
  {
    id: "item-dining-chair",
    projectId: demoProject.id,
    productId: "product-dining-chair",
    supplierId: "supplier-foshan-seating",
    area: "All-day Dining",
    quantity: 24,
    kind: "STANDARD",
    memberUnitPriceSnapshot: "7900.00",
    specificationSnapshot: "โครงไม้สี Walnut, เบาะผ้าสี Olive",
    status: "READY_TO_ORDER",
    customQuotationId: null,
    memberApprovedAt: null,
  },
  {
    id: "item-pendant-light",
    projectId: demoProject.id,
    productId: "product-pendant-light",
    supplierId: "supplier-zhongshan-living",
    area: "All-day Dining",
    quantity: 10,
    kind: "STANDARD",
    memberUnitPriceSnapshot: "9800.00",
    specificationSnapshot: "แก้วฝ้าสี Opal, โลหะสี Brushed Brass",
    status: "READY_TO_ORDER",
    customQuotationId: null,
    memberApprovedAt: null,
  },
] satisfies DemoProjectItem[];

export const demoCustomProjectItems = [
  {
    id: "item-reception-counter",
    projectId: demoProject.id,
    productId: "product-reception-counter",
    supplierId: "supplier-guangzhou-bespoke",
    area: "Lobby",
    quantity: 1,
    kind: "CUSTOM",
    memberUnitPriceSnapshot: null,
    specificationSnapshot: "รอใบเสนอราคาและ Confirmed Spec",
    status: "WAITING_QUOTATION",
    customQuotationId: null,
    memberApprovedAt: null,
  },
  {
    id: "item-upholstered-headboard",
    projectId: demoProject.id,
    productId: "product-upholstered-headboard",
    supplierId: "supplier-guangzhou-bespoke",
    area: "Guest Rooms",
    quantity: 10,
    kind: "CUSTOM",
    memberUnitPriceSnapshot: null,
    specificationSnapshot: "รอใบเสนอราคาและ Confirmed Spec",
    status: "WAITING_QUOTATION",
    customQuotationId: null,
    memberApprovedAt: null,
  },
] satisfies DemoProjectItem[];

export const demoCustomRequest = {
  id: "rfq-riverstone-custom",
  requestNumber: "RFQ-2026-000001",
  projectId: demoProject.id,
  itemIds: ["item-reception-counter", "item-upholstered-headboard"],
  title: "Riverstone Custom Lobby & Guest Room Package",
  specification:
    "Reception Counter ตาม Shop Drawing และ Headboard 10 ชุด พร้อมไฟอ่านหนังสือ",
  status: "SUBMITTED",
  submittedAt: "2026-08-04T03:00:00.000Z",
} satisfies DemoCustomRequest;

const quotationV1Money = calculateMoney("375000.00");
const quotationV2Money = calculateMoney("390000.00");

export const demoQuotations = [
  {
    id: "quotation-riverstone-v1",
    quotationNumber: "QT-2026-000001",
    customRequestId: demoCustomRequest.id,
    version: 1,
    status: "SUPERSEDED",
    subtotal: quotationV1Money.subtotal,
    vatRate: quotationV1Money.vatRate,
    vatAmount: quotationV1Money.vatAmount,
    grandTotal: quotationV1Money.grandTotal,
    leadTimeDays: 50,
    specificationSnapshot:
      "Reception Counter ลามิเนต Walnut และ Headboard แบบมาตรฐาน",
    sentAt: "2026-08-08T04:00:00.000Z",
    acceptedAt: null,
  },
  {
    id: "quotation-riverstone-v2",
    quotationNumber: "QT-2026-000001",
    customRequestId: demoCustomRequest.id,
    version: 2,
    status: "ACCEPTED",
    subtotal: quotationV2Money.subtotal,
    vatRate: quotationV2Money.vatRate,
    vatAmount: quotationV2Money.vatAmount,
    grandTotal: quotationV2Money.grandTotal,
    leadTimeDays: 60,
    specificationSnapshot:
      "Reception Counter วีเนียร์ Walnut พร้อม Cable Management และ Headboard ตาม Confirmed Fabric สี Terracotta",
    sentAt: "2026-08-12T04:00:00.000Z",
    acceptedAt: "2026-08-13T06:30:00.000Z",
  },
] satisfies DemoQuotation[];

export const demoOrderMoney = calculateMoney("900000.00");
export const demoFreightMoney = calculateMoney("90000.00");

export const demoOrder = {
  id: "order-riverstone",
  orderNumber: "ORD-2026-000001",
  projectId: demoProject.id,
  projectItemIds: [
    ...demoStandardProjectItems.map((item) => item.id),
    ...demoCustomProjectItems.map((item) => item.id),
  ],
  subtotal: demoOrderMoney.subtotal,
  vatRate: demoOrderMoney.vatRate,
  vatAmount: demoOrderMoney.vatAmount,
  grandTotal: demoOrderMoney.grandTotal,
  status: "PROCESSING",
  createdAt: "2026-08-14T03:00:00.000Z",
} satisfies DemoOrder;

export const demoPaymentSchedules = [
  {
    id: "schedule-deposit",
    orderId: demoOrder.id,
    type: "DEPOSIT",
    dueAmount: demoOrderMoney.deposit,
    status: "VERIFIED",
    verifiedAmount: demoOrderMoney.deposit,
  },
  {
    id: "schedule-balance",
    orderId: demoOrder.id,
    type: "BALANCE",
    dueAmount: demoOrderMoney.balance,
    status: "PENDING",
    verifiedAmount: "0.00",
  },
] satisfies DemoPaymentSchedule[];

export const demoDepositTransfers = [
  {
    id: "transfer-deposit-1",
    scheduleId: "schedule-deposit",
    reference: "PAY-2026-000001",
    amount: "300000.00",
    submittedAt: "2026-08-15T02:15:00.000Z",
    status: "VERIFIED",
  },
  {
    id: "transfer-deposit-2",
    scheduleId: "schedule-deposit",
    reference: "PAY-2026-000002",
    amount: "181500.00",
    submittedAt: "2026-08-16T02:45:00.000Z",
    status: "VERIFIED",
  },
] satisfies DemoPaymentTransfer[];

export const demoBalanceTransfers = [
  {
    id: "transfer-balance-1",
    scheduleId: "schedule-balance",
    reference: "PAY-2026-000003",
    amount: "200000.00",
    submittedAt: "2026-10-27T02:00:00.000Z",
    status: "VERIFIED",
  },
  {
    id: "transfer-balance-2",
    scheduleId: "schedule-balance",
    reference: "PAY-2026-000004",
    amount: "281500.00",
    submittedAt: "2026-10-28T03:15:00.000Z",
    status: "VERIFIED",
  },
] satisfies DemoPaymentTransfer[];

export const demoSupplierOrders = [
  {
    id: "supplier-order-seating",
    supplierOrderNumber: "PO-2026-000001",
    orderId: demoOrder.id,
    supplierId: "supplier-foshan-seating",
    projectItemIds: ["item-lounge-chair", "item-dining-chair"],
    factoryCostTotal: "198400.00",
    status: "PO_ISSUED",
    supplierDepositPaid: true,
    supplierBalancePaid: false,
  },
  {
    id: "supplier-order-living",
    supplierOrderNumber: "PO-2026-000002",
    orderId: demoOrder.id,
    supplierId: "supplier-zhongshan-living",
    projectItemIds: ["item-side-table", "item-pendant-light"],
    factoryCostTotal: "100600.00",
    status: "PO_ISSUED",
    supplierDepositPaid: true,
    supplierBalancePaid: false,
  },
  {
    id: "supplier-order-bespoke",
    supplierOrderNumber: "PO-2026-000003",
    orderId: demoOrder.id,
    supplierId: "supplier-guangzhou-bespoke",
    projectItemIds: [
      "item-reception-counter",
      "item-upholstered-headboard",
    ],
    factoryCostTotal: "220000.00",
    status: "PO_ISSUED",
    supplierDepositPaid: true,
    supplierBalancePaid: false,
  },
] satisfies DemoSupplierOrder[];

export const demoProductionEvents = [
  {
    id: "production-seating-start",
    supplierOrderId: "supplier-order-seating",
    status: "IN_PRODUCTION",
    occurredAt: "2026-08-21T02:00:00.000Z",
    note: "เริ่มประกอบโครงและบุเบาะ",
    progressPercent: 20,
  },
  {
    id: "production-living-delay",
    supplierOrderId: "supplier-order-living",
    status: "DELAYED",
    occurredAt: "2026-09-28T02:00:00.000Z",
    note: "วัตถุดิบ Brushed Brass มาถึงช้ากว่าแผน 5 วัน",
    progressPercent: 75,
  },
  {
    id: "production-bespoke-complete",
    supplierOrderId: "supplier-order-bespoke",
    status: "PRODUCTION_COMPLETED",
    occurredAt: "2026-10-16T03:00:00.000Z",
    note: "ผลิต Reception Counter และ Headboard ครบ",
    progressPercent: 100,
  },
  {
    id: "production-bespoke-rework",
    supplierOrderId: "supplier-order-bespoke",
    status: "REWORK_REQUIRED",
    occurredAt: "2026-10-18T04:00:00.000Z",
    note: "แก้เฉดสีวีเนียร์ Reception Counter ให้ตรง Approved Sample",
    progressPercent: 95,
  },
  {
    id: "production-bespoke-pass",
    supplierOrderId: "supplier-order-bespoke",
    status: "QC_PASSED",
    occurredAt: "2026-10-25T05:00:00.000Z",
    note: "ตรวจซ้ำผ่านหลังแก้ไขสี",
    progressPercent: 100,
  },
] satisfies DemoProductionEvent[];

export const demoQcInspections = [
  {
    id: "qc-standard-seating",
    projectItemId: "item-lounge-chair",
    result: "PASSED",
    inspectedAt: "2026-10-15T03:00:00.000Z",
    note: "ขนาด สี และงานบุผ่าน Checklist",
    memberVisible: true,
  },
  {
    id: "qc-standard-dining",
    projectItemId: "item-dining-chair",
    result: "PASSED",
    inspectedAt: "2026-10-15T03:15:00.000Z",
    note: "โครงไม้ สี และความแข็งแรงผ่าน Checklist",
    memberVisible: true,
  },
  {
    id: "qc-standard-living",
    projectItemId: "item-side-table",
    result: "PASSED",
    inspectedAt: "2026-10-16T03:00:00.000Z",
    note: "ผิวโต๊ะและสีโลหะผ่าน Checklist",
    memberVisible: true,
  },
  {
    id: "qc-standard-lighting",
    projectItemId: "item-pendant-light",
    result: "PASSED",
    inspectedAt: "2026-10-16T03:15:00.000Z",
    note: "ผิวโลหะ แก้ว และระบบไฟผ่าน Checklist",
    memberVisible: true,
  },
  {
    id: "qc-custom-failed",
    projectItemId: "item-reception-counter",
    result: "FAILED",
    inspectedAt: "2026-10-17T04:00:00.000Z",
    note: "เฉดสีวีเนียร์เข้มกว่า Approved Sample",
    memberVisible: true,
  },
  {
    id: "qc-custom-rework",
    projectItemId: "item-reception-counter",
    result: "REWORK_REQUIRED",
    inspectedAt: "2026-10-18T04:00:00.000Z",
    note: "ส่งกลับแก้ผิวและตรวจใหม่",
    memberVisible: true,
  },
  {
    id: "qc-custom-pass",
    projectItemId: "item-reception-counter",
    result: "PASSED",
    inspectedAt: "2026-10-25T05:00:00.000Z",
    note: "สีและสเปกผ่าน Confirmed Sample",
    memberVisible: true,
  },
  {
    id: "qc-headboard-pass",
    projectItemId: "item-upholstered-headboard",
    result: "PASSED",
    inspectedAt: "2026-10-25T05:15:00.000Z",
    note: "ขนาด ผ้า และระบบไฟอ่านหนังสือผ่าน",
    memberVisible: true,
  },
] satisfies DemoQcInspection[];

export const demoShipments = [
  {
    id: "shipment-standard",
    shipmentNumber: "SHP-2026-000001",
    orderId: demoOrder.id,
    projectItemIds: demoStandardProjectItems.map((item) => item.id),
    status: "IN_TRANSIT",
    shippingMethod: "LCL",
    etd: "2026-11-01",
    eta: "2026-11-18",
    deliveredAt: null,
    deliveryResult: null,
  },
  {
    id: "shipment-custom",
    shipmentNumber: "SHP-2026-000002",
    orderId: demoOrder.id,
    projectItemIds: demoCustomProjectItems.map((item) => item.id),
    status: "IN_TRANSIT",
    shippingMethod: "LCL",
    etd: "2026-11-10",
    eta: "2026-11-26",
    deliveredAt: null,
    deliveryResult: null,
  },
] satisfies DemoShipment[];

export const demoClaim = {
  id: "claim-damaged-chair",
  claimNumber: "CLM-2026-000001",
  orderId: demoOrder.id,
  shipmentId: "shipment-standard",
  projectItemId: "item-lounge-chair",
  issueType: "DAMAGED_IN_TRANSIT",
  description: "เก้าอี้ Lounge Chair จำนวน 1 ตัวมีรอยกระแทกที่มุมพนักพิง",
  status: "SUBMITTED",
  resolution: null,
  memberConfirmedAt: null,
} satisfies DemoClaim;

export const demoDocuments = [
  {
    id: "doc-product-schedule-pdf",
    documentNumber: "PS-PRJ-2026-000001",
    type: "PRODUCT_SCHEDULE_PDF",
    title: "Riverstone Product Schedule",
    visibility: "MEMBER",
    watermark: "DEMO",
    availableFromScene: "PROJECT_CATALOG",
  },
  {
    id: "doc-product-schedule-xlsx",
    documentNumber: "PS-PRJ-2026-000001",
    type: "PRODUCT_SCHEDULE_XLSX",
    title: "Riverstone Product Schedule",
    visibility: "MEMBER",
    watermark: "DEMO",
    availableFromScene: "PROJECT_CATALOG",
  },
  {
    id: "doc-quotation-v1",
    documentNumber: "QT-2026-000001-V1",
    type: "CUSTOM_QUOTATION",
    title: "Custom Quotation Version 1",
    visibility: "MEMBER",
    watermark: "DEMO",
    availableFromScene: "QUOTATION",
  },
  {
    id: "doc-quotation-v2",
    documentNumber: "QT-2026-000001-V2",
    type: "CUSTOM_QUOTATION",
    title: "Custom Quotation Version 2 — Accepted",
    visibility: "MEMBER",
    watermark: "DEMO",
    availableFromScene: "QUOTATION",
  },
  {
    id: "doc-customer-order",
    documentNumber: "ORD-2026-000001",
    type: "CUSTOMER_ORDER",
    title: "Customer Order",
    visibility: "MEMBER",
    watermark: "DEMO",
    availableFromScene: "ORDER_DEPOSIT",
  },
  {
    id: "doc-deposit-notice",
    documentNumber: "INV-DEP-2026-000001",
    type: "PAYMENT_NOTICE",
    title: "ใบแจ้งมัดจำ 50%",
    visibility: "MEMBER",
    watermark: "DEMO",
    availableFromScene: "ORDER_DEPOSIT",
  },
  {
    id: "doc-qc-report",
    documentNumber: "QC-2026-000001",
    type: "QC_REPORT",
    title: "Custom QC and Reinspection Report",
    visibility: "MEMBER",
    watermark: "DEMO",
    availableFromScene: "PRODUCTION_QC",
  },
  {
    id: "doc-balance-notice",
    documentNumber: "INV-BAL-2026-000001",
    type: "PAYMENT_NOTICE",
    title: "ใบแจ้งยอดคงเหลือ 50%",
    visibility: "MEMBER",
    watermark: "DEMO",
    availableFromScene: "APPROVAL_BALANCE",
  },
  {
    id: "doc-packing-list-1",
    documentNumber: "PL-SHP-2026-000001",
    type: "PACKING_LIST",
    title: "Standard Items Packing List",
    visibility: "MEMBER",
    watermark: "DEMO",
    availableFromScene: "PARTIAL_SHIPMENT",
  },
  {
    id: "doc-delivery-proof",
    documentNumber: "POD-2026-000001",
    type: "DELIVERY_PROOF",
    title: "Delivery Proof — Received with Issue",
    visibility: "MEMBER",
    watermark: "DEMO",
    availableFromScene: "DELIVERY_CLAIM",
  },
  {
    id: "doc-claim-resolution",
    documentNumber: "CLM-2026-000001",
    type: "CLAIM_RESOLUTION",
    title: "Claim Replacement Resolution",
    visibility: "MEMBER",
    watermark: "DEMO",
    availableFromScene: "EXECUTIVE_SUMMARY",
  },
  {
    id: "doc-supplier-cost",
    documentNumber: "INT-COST-2026-000001",
    type: "CUSTOMER_ORDER",
    title: "Internal Supplier Cost Summary",
    visibility: "INTERNAL",
    watermark: "DEMO",
    availableFromScene: "ORDER_DEPOSIT",
  },
] satisfies DemoDocument[];
