import {
  Boxes,
  Building2,
  ChartNoAxesCombined,
  ClipboardCheck,
  Factory,
  FileQuestion,
  FolderKanban,
  HandCoins,
  PackageCheck,
  Quote,
  Settings2,
  ShieldCheck,
  Ship,
} from "lucide-react";

export const appModules = [
  {
    slug: "access",
    order: "01",
    label: "บริษัทและสิทธิ์",
    shortLabel: "Access",
    description: "สมาชิก บริษัท ผู้ใช้ หลายบทบาท และการอนุมัติ",
    icon: ShieldCheck,
    accent: "jade",
    actions: ["อนุมัติสมาชิก", "กำหนด Role", "ตรวจ Audit"],
  },
  {
    slug: "catalog",
    order: "02",
    label: "สินค้าและโรงงาน",
    shortLabel: "Catalog",
    description: "Product Master, Supplier, Option และราคาสมาชิก",
    icon: Boxes,
    accent: "brass",
    actions: ["เพิ่มสินค้า", "ตั้งราคา", "Publish"],
  },
  {
    slug: "projects",
    order: "03",
    label: "โครงการ",
    shortLabel: "Projects",
    description: "ลูกค้าปลายทาง พื้นที่ และ Product Schedule",
    icon: FolderKanban,
    accent: "jade",
    actions: ["สร้างโครงการ", "เพิ่มรายการ", "ดาวน์โหลด Schedule"],
  },
  {
    slug: "rfq",
    order: "04",
    label: "Custom RFQ",
    shortLabel: "RFQ",
    description: "รับสเปก ไฟล์ และคำขอราคาสินค้า Custom",
    icon: FileQuestion,
    accent: "lacquer",
    actions: ["ส่งคำขอ", "ขอข้อมูลเพิ่ม", "พร้อมเสนอราคา"],
  },
  {
    slug: "quotations",
    order: "05",
    label: "ใบเสนอราคา",
    shortLabel: "Quotation",
    description: "Quotation ในนาม GISP แบบ Version และ Snapshot",
    icon: Quote,
    accent: "brass",
    actions: ["สร้าง Revision", "ส่งให้สมาชิก", "Accept / Reject"],
  },
  {
    slug: "orders",
    order: "06",
    label: "ออเดอร์และชำระเงิน",
    shortLabel: "Orders",
    description: "50/50, Partial Transfer, Finance Verify และ Supplier PO",
    icon: HandCoins,
    accent: "lacquer",
    actions: ["สร้างออเดอร์", "ตรวจยอดสะสม", "ออก PO"],
  },
  {
    slug: "production",
    order: "07",
    label: "ผลิตและ QC",
    shortLabel: "Production",
    description: "ETA, Delay, Checklist, Rework และ Member Approval",
    icon: Factory,
    accent: "jade",
    actions: ["อัปเดตการผลิต", "บันทึก QC", "ขอตรวจซ้ำ"],
  },
  {
    slug: "shipments",
    order: "08",
    label: "ขนส่งและส่งมอบ",
    shortLabel: "Logistics",
    description: "คลังจีน รวมตู้ Tracking นัดส่ง และหลักฐาน",
    icon: Ship,
    accent: "brass",
    actions: ["ตรวจ Dispatch Gate", "สร้าง Shipment", "บันทึก Delivery"],
  },
  {
    slug: "claims",
    order: "09",
    label: "เคลม",
    shortLabel: "Claims",
    description: "หลักฐาน แนวทางแก้ไข และ Timeline",
    icon: ClipboardCheck,
    accent: "lacquer",
    actions: ["เปิดเคลม", "เสนอ Resolution", "ยืนยันปิด"],
  },
  {
    slug: "reports",
    order: "10",
    label: "Dashboard และรายงาน",
    shortLabel: "Reports",
    description: "Order, Payment, Delay, Delivery และ Claim",
    icon: ChartNoAxesCombined,
    accent: "jade",
    actions: ["Action Required", "ดูสรุป", "เปิดรายงานคงที่"],
  },
] as const;

export const secondaryModules = [
  { slug: "suppliers", label: "Suppliers", icon: Building2 },
  { slug: "deliveries", label: "Deliveries", icon: PackageCheck },
  { slug: "settings", label: "Settings", icon: Settings2 },
] as const;

export type ModuleSlug = (typeof appModules)[number]["slug"];

export function findModule(slug: string) {
  return appModules.find((module) => module.slug === slug);
}
