"use client";

import { ArrowLeft, CheckCircle2, ExternalLink, FileUp, RefreshCw, ShieldAlert } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { claimIssueLabels, claimStatusLabels, claimTone, resolutionLabels, responsibilityLabels, type ClaimDetail } from "@/lib/claims/types";

export function AdminClaimDetail({ claimId }: { claimId: string }) {
  const [data, setData] = useState<ClaimDetail>(); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>(); const [message, setMessage] = useState<string>();
  const [decisionMode, setDecisionMode] = useState<"REQUEST_INFORMATION" | "REJECT" | "REOPEN" | null>(null);
  const load = useCallback(async () => { const response = await fetch(`/api/admin/claims/${claimId}`, { cache: "no-store" }); const body = await response.json() as { data?: ClaimDetail; message?: string }; if (!response.ok || !body.data) setError(body.message ?? "โหลด Claim ไม่สำเร็จ"); else setData(body.data); }, [claimId]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function action(payload: Record<string, unknown>) { setBusy(true); setError(undefined); setMessage(undefined); try { const response = await fetch(`/api/admin/claims/${claimId}/actions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json() as { message?: string }; if (!response.ok) throw new Error(body.message ?? "อัปเดต Claim ไม่สำเร็จ"); setMessage(body.message); setDecisionMode(null); await load(); return true; } catch (caught) { setError(caught instanceof Error ? caught.message : "อัปเดต Claim ไม่สำเร็จ"); return false; } finally { setBusy(false); } }
  async function complete(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(undefined); const formElement = event.currentTarget; const form = new FormData(formElement); try { const file = form.get("file"); if (!(file instanceof File) || !file.size) throw new Error("ต้องแนบหลักฐานผลดำเนินการ"); const upload = new FormData(); upload.set("file", file); if (data?.claim.member_profile_id) upload.set("memberProfileId", data.claim.member_profile_id); const uploadResponse = await fetch("/api/claims/evidence", { method: "POST", body: upload }); const uploadBody = await uploadResponse.json() as { data?: { id: string }; message?: string }; if (!uploadResponse.ok || !uploadBody.data?.id) throw new Error(uploadBody.message ?? "อัปโหลดหลักฐานไม่สำเร็จ"); await action({ action: "COMPLETE_RESOLUTION", note: form.get("note"), evidence_file_id: uploadBody.data.id }); formElement.reset(); } catch (caught) { setError(caught instanceof Error ? caught.message : "บันทึกผลไม่สำเร็จ"); setBusy(false); } }
  async function internalCost(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(undefined); const formElement = event.currentTarget; const form = new FormData(formElement); try { const response = await fetch(`/api/admin/claims/${claimId}/internal-costs`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cost_type: form.get("cost_type"), amount: form.get("amount"), currency: "THB", note: form.get("note") }) }); const body = await response.json() as { message?: string }; if (!response.ok) throw new Error(body.message ?? "บันทึกต้นทุนไม่สำเร็จ"); setMessage(body.message); formElement.reset(); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "บันทึกต้นทุนไม่สำเร็จ"); } finally { setBusy(false); } }
  if (!data) return <div className="v14-panel v14-empty">{error ?? "กำลังโหลด Claim…"}</div>;
  const { claim } = data; const warranty = claim.warranty_snapshot ?? {}; const final = ["CLOSED", "REJECTED"].includes(claim.status);
  return <main className="claim-detail admin-claim-detail"><Link href="/admin/claims" className="member-detail__back"><ArrowLeft/>กลับ Claim Queue</Link><section className="quotation-detail__hero"><div><p className="v14-eyebrow">{claim.claim_number} · {claim.order_number}</p><h1>{claim.subject}</h1><p>{claim.company_name} · {claim.item_name} · จำนวน {claim.claimed_quantity}</p></div><span className={`v14-status v14-status--${claimTone(claim.status)}`}><small>สถานะปัจจุบัน</small>{claimStatusLabels[claim.status] ?? claim.status}</span></section>{error ? <p className="v14-alert">{error}</p> : null}{message ? <p className="quotation-success">{message}</p> : null}
    <section className="v14-panel claim-command"><div className="v14-panel__head"><div><p className="v14-eyebrow">Order Admin controls</p><h2>ขั้นตอนดำเนินการ</h2></div><button onClick={() => void load()} className="v14-button v14-button--outline v14-button--small"><RefreshCw size={14}/>โหลดใหม่</button></div><div className="v14-actions">{["SUBMITTED", "WAITING_INFORMATION"].includes(claim.status) ? <button disabled={busy} onClick={() => void action({ action: "START_REVIEW", note: "รับเคสเข้าตรวจสอบ" })} className="v14-button v14-button--dark">เริ่มตรวจสอบ</button> : null}{!final ? <button disabled={busy} onClick={() => setDecisionMode(decisionMode === "REQUEST_INFORMATION" ? null : "REQUEST_INFORMATION")} className="v14-button v14-button--outline">ขอข้อมูลเพิ่ม</button> : null}{claim.status === "RESOLVED" && claim.member_confirmed_at ? <button disabled={busy} onClick={() => void action({ action: "CLOSE", note: "ตรวจทานผลและคำยืนยันของสมาชิกแล้ว" })} className="v14-button v14-button--dark"><CheckCircle2 size={15}/>ปิด Claim</button> : null}{!final ? <button disabled={busy} onClick={() => setDecisionMode(decisionMode === "REJECT" ? null : "REJECT")} className="v14-button v14-button--outline">ไม่รับ Claim</button> : <button disabled={busy} onClick={() => setDecisionMode(decisionMode === "REOPEN" ? null : "REOPEN")} className="v14-button v14-button--outline">เปิดเคสอีกครั้ง</button>}</div>{decisionMode ? <form className="claim-decision-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void action({ action: decisionMode, note: form.get("note") }); }}><label>{decisionMode === "REQUEST_INFORMATION" ? "ข้อมูลที่ต้องการจากสมาชิก" : decisionMode === "REJECT" ? "เหตุผลที่ไม่รับ Claim" : "เหตุผลที่เปิดเคสอีกครั้ง"}<textarea name="note" rows={3} minLength={3} autoFocus required placeholder={decisionMode === "REQUEST_INFORMATION" ? "เช่น ขอภาพมุมกล่องเพิ่มเติม" : "ระบุเหตุผลอย่างน้อย 3 ตัวอักษร"}/></label><div className="v14-actions"><button disabled={busy} className="v14-button v14-button--dark">ยืนยันและบันทึก</button><button type="button" disabled={busy} onClick={() => setDecisionMode(null)} className="v14-button v14-button--outline">ยกเลิก</button></div></form> : null}</section>
    <section className="claim-detail__grid"><article className="v14-panel"><p className="v14-eyebrow">Issue review</p><h2>{claimIssueLabels[claim.issue_type] ?? claim.issue_type}</h2><p className="claim-description">{claim.description}</p><dl className="claim-facts"><div><dt>ระดับ</dt><dd>{claim.severity}</dd></div><div><dt>วันที่พบ</dt><dd>{new Date(claim.discovered_at).toLocaleString("th-TH")}</dd></div><div><dt>บรรจุภัณฑ์</dt><dd>{claim.packaging_condition ?? "ไม่ได้ระบุ"}</dd></div><div><dt>การแก้ชั่วคราว</dt><dd>{claim.temporary_action ?? "ไม่ได้ระบุ"}</dd></div></dl></article><aside><article className="v14-panel claim-warranty"><p className="v14-eyebrow">Immutable Warranty Snapshot</p><h2>{String(warranty.title ?? "เงื่อนไขรับประกัน")}</h2><p>{String(warranty.member_summary ?? "—")}</p><details><summary>ดูเงื่อนไขฉบับเต็ม</summary><p>{String(warranty.terms_text ?? "—")}</p></details></article><article className="v14-panel"><p className="v14-eyebrow">Responsibility confirmation</p><h2>ยืนยันผู้รับผิดชอบ</h2><p>ระบบแนะนำ: <b>{responsibilityLabels[claim.suggested_responsibility] ?? claim.suggested_responsibility}</b></p><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void action({ action: "CONFIRM_RESPONSIBILITY", responsibility: form.get("responsibility") }); }} className="claim-inline-form"><select name="responsibility" defaultValue={claim.confirmed_responsibility ?? claim.suggested_responsibility}>{Object.entries(responsibilityLabels).filter(([value]) => value !== "UNDETERMINED").map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button disabled={busy || final} className="v14-button v14-button--dark">ยืนยันความรับผิดชอบ</button></form>{claim.confirmed_responsibility ? <p className="quotation-success">ยืนยันแล้ว: {responsibilityLabels[claim.confirmed_responsibility]}</p> : null}</article></aside></section>
    {!final && claim.confirmed_responsibility ? <section className="v14-panel"><div className="v14-panel__head"><div><p className="v14-eyebrow">Resolution plan</p><h2>เสนอแนวทางแก้ไข</h2></div><ShieldAlert/></div><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void action({ action: "PROPOSE_RESOLUTION", resolution_type: form.get("resolution_type"), note: form.get("note"), target_resolution_at: form.get("target") ? new Date(String(form.get("target"))).toISOString() : undefined }); }} className="claim-resolution-form"><label>วิธีแก้ไข<select name="resolution_type" defaultValue={claim.resolution_type ?? "REPAIR"}>{Object.entries(resolutionLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>เป้าหมายเสร็จ<input name="target" type="datetime-local"/></label><label className="claim-form__wide">รายละเอียด<textarea name="note" minLength={5} rows={3} defaultValue={claim.resolution_details ?? ""} required/></label><button disabled={busy} className="v14-button v14-button--dark">บันทึก Resolution</button>{claim.resolution_type ? <button type="button" disabled={busy} onClick={() => void action({ action: "MARK_IN_PROGRESS", note: "เริ่มดำเนินการตามแผน" })} className="v14-button v14-button--outline">เริ่มดำเนินการ</button> : null}</form><p className="claim-rule-note">Compensation/Credit เป็นเพียงข้อเสนอ ต้องผ่านการอนุมัติและไม่จ่ายอัตโนมัติ</p></section> : null}
    {claim.resolution_type && !["RESOLVED", "CLOSED", "REJECTED"].includes(claim.status) ? <section className="v14-panel"><div className="v14-panel__head"><div><p className="v14-eyebrow">Execution evidence</p><h2>บันทึกผลดำเนินการ</h2></div><FileUp/></div><form onSubmit={complete} className="claim-inline-form"><textarea name="note" minLength={3} rows={3} placeholder="สรุปสิ่งที่ดำเนินการแล้ว" required/><input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png,.mp4" required/><button disabled={busy} className="v14-button v14-button--dark">ดำเนินการเสร็จและรอสมาชิกยืนยัน</button></form></section> : null}
    <section className="claim-detail__grid"><article className="v14-panel"><div className="v14-panel__head"><div><p className="v14-eyebrow">Evidence</p><h2>หลักฐานทั้งหมด</h2></div></div><div className="claim-files">{data.evidence.map((item) => <a key={item.id} href={`/api/claims/evidence/${item.file_id}?redirect=1`} target="_blank" rel="noreferrer"><FileUp/><span><b>{item.file?.original_name ?? "ไฟล์หลักฐาน"}</b><small>{item.evidence_type} · {new Date(item.created_at).toLocaleString("th-TH")}</small></span><ExternalLink/></a>)}</div></article><article className="v14-panel"><p className="v14-eyebrow">Timeline</p><h2>ประวัติ Claim</h2><div className="quotation-timeline">{data.events.map((event) => <article key={event.id}><span/><div><b>{claimStatusLabels[event.action] ?? event.action.replaceAll("_", " ")}</b><p>{event.note ?? "อัปเดต Claim"}</p><small>{new Date(event.created_at).toLocaleString("th-TH")}</small></div></article>)}</div></article></section>
    <section className="v14-panel claim-internal"><div className="v14-panel__head"><div><p className="v14-eyebrow">Internal confidential</p><h2>ต้นทุนภายใน GISP</h2></div><small>สมาชิกจะไม่เห็นข้อมูลส่วนนี้</small></div><div className="claim-cost-list">{data.internalCosts?.map((cost) => <div key={cost.id}><span><b>{cost.cost_type}</b><small>{cost.internal_note ?? "ไม่มีหมายเหตุ"}</small></span><strong>{Number(cost.amount).toLocaleString("th-TH", { style: "currency", currency: cost.currency })}</strong></div>)}</div><form className="claim-cost-form" onSubmit={internalCost}><input name="cost_type" placeholder="ประเภทต้นทุน" required/><input name="amount" type="number" min="0" step="0.01" placeholder="จำนวน" required/><input name="note" placeholder="หมายเหตุภายใน"/><button disabled={busy} className="v14-button v14-button--outline">บันทึกต้นทุน</button></form></section>
  </main>;
}
