"use client";

import { AlertTriangle, Check, Download, LoaderCircle, Upload, X } from "lucide-react";
import { useCallback,useState } from "react";

type PreviewRow={id:string;row_key:string;detail_status:string;cost_status:string|null;baseline_detail:Record<string,unknown>;proposed_detail:Record<string,unknown>|null;detail_diff:Record<string,unknown>;baseline_cost?:Record<string,unknown>|null;proposed_cost?:Record<string,unknown>|null;cost_diff?:Record<string,unknown>;price_preview?:Record<string,unknown>|null;error_codes:string[];warning_codes:string[]};
type Preview={batch:Record<string,unknown>;rows:PreviewRow[];pagination:{page:number;pageSize:number;total:number;totalPages:number}};
type Notice={kind:"good"|"bad";text:string};

async function responseJson(response:Response){const body=await response.json();if(!response.ok)throw new Error(body.message??"ดำเนินการไม่สำเร็จ");return body.data;}
export function CatalogEnrichmentPanel({jobId,initialBatchId,canManage,canReadCosts,canManageCosts,onNotice}:{jobId:string;initialBatchId:string|null;canManage:boolean;canReadCosts:boolean;canManageCosts:boolean;onNotice:(notice:Notice)=>void}){
  const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState<Preview|null>(null);const[checkedDetails,setCheckedDetails]=useState<string[]>([]);const[checkedCosts,setCheckedCosts]=useState<string[]>([]);const[busy,setBusy]=useState<string|null>(null);
  const load=useCallback(async(batchId:string,page=1)=>{const next=await responseJson(await fetch(`/api/admin/catalog/imports/${jobId}/enrichment/${batchId}?page=${page}&pageSize=50`,{cache:"no-store"}));setPreview(next);setCheckedDetails([]);setCheckedCosts([]);},[jobId]);
  function openPreview(batchId:string,page=1){void load(batchId,page).catch(error=>onNotice({kind:"bad",text:error instanceof Error?error.message:"เปิด Preview ไม่สำเร็จ"}));}
  async function upload(){if(!file)return;setBusy("upload");try{const form=new FormData();form.set("file",file);const result=await responseJson(await fetch(`/api/admin/catalog/imports/${jobId}/enrichment/uploads`,{method:"POST",body:form}));await load(result.batchId);onNotice({kind:"good",text:"อัปโหลด Excel และสร้าง Preview แล้ว"});}catch(error){onNotice({kind:"bad",text:error instanceof Error?error.message:"อัปโหลดไม่สำเร็จ"});}finally{setBusy(null);}}
  async function apply(kind:"details"|"costs",rowIds:string[]){if(!preview||!rowIds.length||!window.confirm(`ยืนยัน ${kind==="details"?"รายละเอียดสินค้า":"ต้นทุน"} ${rowIds.length} รายการ?`))return;setBusy(kind);try{await responseJson(await fetch(`/api/admin/catalog/imports/${jobId}/enrichment/${preview.batch.id}/apply-${kind}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rowIds,idempotencyKey:crypto.randomUUID(),confirmed:true})}));await load(String(preview.batch.id),preview.pagination.page);if(kind==="details")setCheckedDetails([]);else setCheckedCosts([]);onNotice({kind:"good",text:kind==="details"?"Apply รายละเอียดแล้ว":"สร้าง Cost Version แล้ว; Member Price ยังไม่ถูก Activate"});}catch(error){onNotice({kind:"bad",text:error instanceof Error?error.message:"Apply ไม่สำเร็จ"});}finally{setBusy(null);}}
  async function cancel(){if(!preview||!window.confirm("ยกเลิกเฉพาะส่วนที่ยังไม่ Apply?"))return;setBusy("cancel");try{await responseJson(await fetch(`/api/admin/catalog/imports/${jobId}/enrichment/${preview.batch.id}/cancel`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirmed:true})}));await load(String(preview.batch.id));onNotice({kind:"good",text:"ยกเลิกส่วนที่ยังไม่ Apply แล้ว"});}catch(error){onNotice({kind:"bad",text:error instanceof Error?error.message:"ยกเลิกไม่สำเร็จ"});}finally{setBusy(null);}}
  const readyDetails=preview?.rows.filter(row=>row.detail_status==="READY")??[];const readyCosts=preview?.rows.filter(row=>row.cost_status==="READY")??[];
  return <section className="space-y-4 rounded border border-black/10 p-4" aria-label="PDF Catalog Excel Round-trip">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="v14-eyebrow">Excel round-trip</p><h3 className="font-semibold">แก้หลายรายการด้วย Excel</h3><p className="text-xs text-black/55">ช่องว่าง = คงค่าเดิม · #CLEAR ใช้ได้เฉพาะข้อมูลสินค้าไม่บังคับ</p></div><div className="flex gap-2">{initialBatchId&&!preview?<button type="button" className="v14-button v14-button--outline" onClick={()=>openPreview(initialBatchId)}>เปิด Preview ล่าสุด</button>:null}<a className="v14-button v14-button--outline" href={`/api/admin/catalog/imports/${jobId}/enrichment/export`}><Download size={14}/>Export Excel</a></div></div>
    <div className="flex flex-wrap items-end gap-3"><label className="min-w-64 flex-1 text-sm">Upload Excel กลับ<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event=>setFile(event.target.files?.[0]??null)}/></label><button type="button" className="v14-button v14-button--dark" disabled={!file||!!busy} onClick={()=>void upload()}>{busy==="upload"?<LoaderCircle className="animate-spin" size={14}/>:<Upload size={14}/>}สร้าง Preview</button></div>
    {preview?<><div className="grid gap-2 sm:grid-cols-5">{[["พร้อมรายละเอียด",preview.batch.ready_detail_rows],["พร้อมต้นทุน",canReadCosts?preview.batch.ready_cost_rows:"—"],["ไม่เปลี่ยน",preview.batch.unchanged_rows],["ผิด/ขัดแย้ง",Number(preview.batch.invalid_rows??0)+Number(preview.batch.conflict_rows??0)],["รอ Draft",canReadCosts?preview.batch.waiting_for_draft_rows:"—"]].map(([label,value])=><div key={String(label)} className="border border-black/10 p-2 text-xs"><span className="block text-black/50">{String(label)}</span><strong>{String(value??0)}</strong></div>)}</div>
      <div className="max-h-96 overflow-auto border border-black/10"><table className="w-full min-w-[900px] text-left text-xs"><thead className="sticky top-0 bg-[#f3f0e9]"><tr><th className="p-2">เลือก</th><th className="p-2">รายละเอียด</th><th className="p-2">ต้นทุน</th><th className="p-2">ก่อน → หลัง</th><th className="p-2">ผลตรวจ</th></tr></thead><tbody>{preview.rows.map(row=><tr key={row.id} className="border-t border-black/10 align-top"><td className="p-2"><label><input aria-label="เลือกรายละเอียด" type="checkbox" disabled={row.detail_status!=="READY"} checked={checkedDetails.includes(row.id)} onChange={e=>setCheckedDetails(current=>e.target.checked?[...current,row.id]:current.filter(id=>id!==row.id))}/> รายละเอียด</label>{canReadCosts?<label className="mt-1 block"><input aria-label="เลือกต้นทุน" type="checkbox" disabled={row.cost_status!=="READY"} checked={checkedCosts.includes(row.id)} onChange={e=>setCheckedCosts(current=>e.target.checked?[...current,row.id]:current.filter(id=>id!==row.id))}/> ต้นทุน</label>:null}</td><td className="p-2"><strong>{row.detail_status}</strong></td><td className="p-2">{canReadCosts?row.cost_status:"ไม่มีสิทธิ์ดู"}</td><td className="p-2"><strong>รายละเอียด</strong><pre className="max-w-md whitespace-pre-wrap">{JSON.stringify({ก่อน:row.baseline_detail,หลัง:{...row.baseline_detail,...row.detail_diff}},null,2)}</pre>{canReadCosts&&row.proposed_cost?<><strong>ต้นทุน</strong><pre className="max-w-md whitespace-pre-wrap">{JSON.stringify({ก่อน:row.baseline_cost??null,หลัง:{...(row.baseline_cost??{}),...(row.cost_diff??row.proposed_cost)}},null,2)}</pre></>:null}</td><td className="p-2">{row.error_codes?.length?<span className="text-[#a83226]"><AlertTriangle size={13}/>{row.error_codes.join(", ")}</span>:<span className="text-[#356b52]"><Check size={13}/>พร้อม</span>}</td></tr>)}</tbody></table></div>
      <div className="flex flex-wrap gap-2"><button type="button" className="v14-button v14-button--dark" disabled={!canManage||!checkedDetails.length||!!busy} onClick={()=>void apply("details",checkedDetails)}>ยืนยันรายละเอียดสินค้า ({checkedDetails.length}/{readyDetails.length})</button>{canReadCosts?<button type="button" className="v14-button v14-button--dark" disabled={!canManageCosts||!checkedCosts.length||!!busy} onClick={()=>void apply("costs",checkedCosts)}>ยืนยันต้นทุน ({checkedCosts.length}/{readyCosts.length})</button>:null}<button type="button" className="v14-button v14-button--outline" disabled={!!busy} onClick={()=>void cancel()}><X size={14}/>ยกเลิกส่วนที่ยังไม่ Apply</button></div>
      {canReadCosts?<p className="text-xs text-black/55">ราคาสมาชิกด้านล่างเป็นเพียง Preview เท่านั้น ต้องไป Activate ในหน้าจอ Pricing ตามขั้นตอนเดิม</p>:null}
      {preview.pagination.totalPages>1?<div className="flex justify-end gap-2"><button type="button" disabled={preview.pagination.page<=1} onClick={()=>openPreview(String(preview.batch.id),preview.pagination.page-1)}>ก่อนหน้า</button><span>{preview.pagination.page}/{preview.pagination.totalPages}</span><button type="button" disabled={preview.pagination.page>=preview.pagination.totalPages} onClick={()=>openPreview(String(preview.batch.id),preview.pagination.page+1)}>ถัดไป</button></div>:null}</>:null}
  </section>;
}
