"use client";

import { AlertTriangle, Check, Download, LoaderCircle, Upload, X } from "lucide-react";
import Link from "next/link";
import { useCallback,useState } from "react";

export type PreviewRow={id:string;row_key:string;product_id?:string|null;applied_product_id?:string|null;detail_status:string;cost_status:string|null;baseline_detail:Record<string,unknown>;proposed_detail:Record<string,unknown>|null;detail_diff:Record<string,unknown>;baseline_cost?:Record<string,unknown>|null;proposed_cost?:Record<string,unknown>|null;cost_diff?:Record<string,unknown>;price_preview?:Record<string,unknown>|null;error_codes:string[];warning_codes:string[]};
type Preview={batch:Record<string,unknown>;rows:PreviewRow[];pagination:{page:number;pageSize:number;total:number;totalPages:number}};
type Notice={kind:"good"|"bad";text:string};
const previewMoney=new Intl.NumberFormat("th-TH-u-nu-latn",{minimumFractionDigits:2,maximumFractionDigits:2});
const previewNumber=new Intl.NumberFormat("th-TH-u-nu-latn",{maximumFractionDigits:4});
const detailFieldLabels:Record<string,string>={sku:"รหัสสินค้า (SKU)",factory_sku:"รหัสโรงงาน",name_th:"ชื่อสินค้า (ไทย)",name_en:"ชื่อสินค้า (อังกฤษ)",name_zh:"ชื่อสินค้า (จีน)",product_type:"ประเภทสินค้า",category_id:"หมวดสินค้า",category_code:"รหัสหมวดสินค้า",country_code:"ประเทศ",lead_time_days:"ระยะเวลาผลิต (วัน)",width_mm:"ความกว้าง (มม.)",depth_mm:"ความลึก (มม.)",height_mm:"ความสูง (มม.)",weight_kg:"น้ำหนัก (กก.)",cbm:"ปริมาตร (CBM)",material_summary:"วัสดุ",finish_summary:"ผิวสำเร็จ",moq:"จำนวนสั่งซื้อขั้นต่ำ",description_th:"คำอธิบายสินค้า",specification_summary:"ข้อมูลจำเพาะ"};
const costFieldLabels:Record<string,string>={factory_cost:"ต้นทุนโรงงาน",currency:"สกุลเงิน",exchange_rate_to_thb:"อัตราแลกเปลี่ยนเป็นบาท",effective_from:"วันที่เริ่มใช้"};
const productTypeLabels:Record<string,string>={STANDARD:"สินค้ามาตรฐาน",CUSTOM_TEMPLATE:"สั่งผลิตตามแบบ",READY_TO_ORDER:"พร้อมสั่ง",BUILT_IN:"บิลท์อิน",MATERIAL:"วัสดุ",EQUIPMENT:"อุปกรณ์",DECORATIVE:"ของตกแต่ง"};
const statusLabels:Record<string,string>={READY:"พร้อมยืนยัน",UNCHANGED:"ไม่เปลี่ยนแปลง",INVALID:"ไม่ถูกต้อง",CONFLICT:"ข้อมูลต้นฉบับเปลี่ยน",WAITING_FOR_DRAFT:"รอสร้าง Product Draft",APPLIED:"ยืนยันแล้ว",CANCELLED:"ยกเลิกแล้ว"};
const errorLabels:Record<string,string>={DUPLICATE_SKU_IN_WORKBOOK:"SKU ซ้ำในไฟล์ Excel",DUPLICATE_SKU_IN_DATABASE:"SKU ซ้ำกับสินค้าเดิม",CATEGORY_NOT_FOUND:"ไม่พบหมวดสินค้า",COUNTRY_NOT_FOUND:"ไม่พบประเทศ",COST_FIELDS_REQUIRED:"กรอกข้อมูลต้นทุนไม่ครบ",CLEAR_NOT_ALLOWED:"ห้ามใช้ #CLEAR กับฟิลด์นี้",EFFECTIVE_FROM_INVALID:"วันที่เริ่มใช้ไม่ถูกต้อง"};

export type EnrichmentChangeRow={field:string;label:string;before:string;after:string};
export function formatEnrichmentPreviewValue(value:unknown,field:string,position:"before"|"after"="after"){
  if(value===null||value===undefined||value==="")return "—";
  if(field==="category_id")return position==="before"?"หมวดสินค้าปัจจุบัน":"หมวดสินค้าที่เลือกใหม่";
  if(field==="product_type")return productTypeLabels[String(value)]??String(value);
  if(field==="effective_from"&&typeof value==="string")return value.slice(0,10)||"—";
  if(typeof value==="number")return previewNumber.format(value);
  if(typeof value==="boolean")return value?"ใช่":"ไม่ใช่";
  return typeof value==="string"?value:"—";
}
function changeRows(before:Record<string,unknown>|null|undefined,diff:Record<string,unknown>|null|undefined,labels:Record<string,string>){
  return Object.keys(labels).flatMap((field):EnrichmentChangeRow[]=>{
    if(!diff||!Object.prototype.hasOwnProperty.call(diff,field))return [];
    const beforeText=formatEnrichmentPreviewValue(before?.[field],field,"before");const afterText=formatEnrichmentPreviewValue(diff[field],field,"after");
    return beforeText===afterText?[]:[{field,label:labels[field],before:beforeText,after:afterText}];
  });
}
export function enrichmentPreviewView(row:Pick<PreviewRow,"baseline_detail"|"detail_diff"|"baseline_cost"|"cost_diff"|"proposed_cost">,canReadCosts=true){
  const afterDetail={...row.baseline_detail,...row.detail_diff};
  const detailChanges=changeRows(row.baseline_detail,row.detail_diff,detailFieldLabels);
  const costChanges=canReadCosts?changeRows(row.baseline_cost,row.cost_diff??row.proposed_cost,costFieldLabels):[];
  return{sku:formatEnrichmentPreviewValue(afterDetail.sku,"sku"),name:formatEnrichmentPreviewValue(afterDetail.name_th??afterDetail.name_en??afterDetail.name_zh,"name_th"),detailChanges,costChanges,unchanged:detailChanges.length===0&&costChanges.length===0};
}
export function enrichmentStatusLabel(status:string|null|undefined){return status?statusLabels[status]??status:"—";}

export function memberPricePreviewView(preview:Record<string,unknown>|null|undefined){if(preview?.memberPrice===null||preview?.memberPrice===undefined||preview.memberPrice==="")return null;const amount=Number(preview.memberPrice);if(!Number.isFinite(amount))return null;return{amountText:previewMoney.format(amount),currency:"THB",statusText:"ยังไม่เปิดใช้ราคา"};}
export function enrichmentRowIssueLabel(row:Pick<PreviewRow,"detail_status"|"cost_status"|"error_codes">){if(row.error_codes?.length)return row.error_codes.map(code=>errorLabels[code]??code).join(", ");const states=[row.detail_status,row.cost_status].filter((status)=>status==="INVALID"||status==="CONFLICT");return states.length?states.map(status=>enrichmentStatusLabel(status)).join(", "):null;}

function ChangeTable({title,changes}:{title:string;changes:EnrichmentChangeRow[]}){if(!changes.length)return null;return <div className="space-y-1"><strong className="block">{title}</strong><div className="overflow-x-auto rounded border border-black/10"><table className="w-full min-w-[420px] text-left"><thead className="bg-[#f3f0e9] text-black/65"><tr><th className="p-2">ชื่อฟิลด์</th><th className="p-2">ค่าเดิม</th><th className="p-2">ค่าใหม่</th></tr></thead><tbody>{changes.map(change=><tr key={change.field} className="border-t border-black/10"><th scope="row" className="p-2 font-medium">{change.label}</th><td className="p-2 text-black/60">{change.before}</td><td className="p-2 font-medium">{change.after}</td></tr>)}</tbody></table></div></div>;}

async function responseJson(response:Response){const body=await response.json();if(!response.ok)throw new Error(body.message??"ดำเนินการไม่สำเร็จ");return body.data;}
export function CatalogEnrichmentPanel({jobId,initialBatchId,canManage,canReadCosts,canManageCosts,onNotice}:{jobId:string;initialBatchId:string|null;canManage:boolean;canReadCosts:boolean;canManageCosts:boolean;onNotice:(notice:Notice)=>void}){
  const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState<Preview|null>(null);const[checkedDetails,setCheckedDetails]=useState<string[]>([]);const[checkedCosts,setCheckedCosts]=useState<string[]>([]);const[busy,setBusy]=useState<string|null>(null);
  const load=useCallback(async(batchId:string,page=1)=>{const next=await responseJson(await fetch(`/api/admin/catalog/imports/${jobId}/enrichment/${batchId}?page=${page}&pageSize=50`,{cache:"no-store"}));setPreview(next);setCheckedDetails([]);setCheckedCosts([]);},[jobId]);
  function openPreview(batchId:string,page=1){void load(batchId,page).catch(error=>onNotice({kind:"bad",text:error instanceof Error?error.message:"เปิด Preview ไม่สำเร็จ"}));}
  async function upload(){if(!file)return;setBusy("upload");try{const form=new FormData();form.set("file",file);const result=await responseJson(await fetch(`/api/admin/catalog/imports/${jobId}/enrichment/uploads`,{method:"POST",body:form}));await load(result.batchId);onNotice({kind:"good",text:"อัปโหลด Excel และสร้าง Preview แล้ว"});}catch(error){onNotice({kind:"bad",text:error instanceof Error?error.message:"อัปโหลดไม่สำเร็จ"});}finally{setBusy(null);}}
  async function apply(kind:"details"|"costs",rowIds:string[]){if(!preview||!rowIds.length||!window.confirm(`ยืนยัน ${kind==="details"?"รายละเอียดสินค้า":"ต้นทุน"} ${rowIds.length} รายการ?`))return;setBusy(kind);try{await responseJson(await fetch(`/api/admin/catalog/imports/${jobId}/enrichment/${preview.batch.id}/apply-${kind}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rowIds,idempotencyKey:crypto.randomUUID(),confirmed:true})}));await load(String(preview.batch.id),preview.pagination.page);if(kind==="details")setCheckedDetails([]);else setCheckedCosts([]);onNotice({kind:"good",text:kind==="details"?"Apply รายละเอียดแล้ว":"สร้าง Cost Version แล้ว; Member Price ยังไม่ถูก Activate"});}catch(error){onNotice({kind:"bad",text:error instanceof Error?error.message:"Apply ไม่สำเร็จ"});}finally{setBusy(null);}}
  async function cancel(){if(!preview||!window.confirm("ยกเลิกเฉพาะส่วนที่ยังไม่ Apply?"))return;setBusy("cancel");try{await responseJson(await fetch(`/api/admin/catalog/imports/${jobId}/enrichment/${preview.batch.id}/cancel`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirmed:true})}));await load(String(preview.batch.id));onNotice({kind:"good",text:"ยกเลิกส่วนที่ยังไม่ Apply แล้ว"});}catch(error){onNotice({kind:"bad",text:error instanceof Error?error.message:"ยกเลิกไม่สำเร็จ"});}finally{setBusy(null);}}
  const readyDetails=preview?.rows.filter(row=>row.detail_status==="READY")??[];const readyCosts=preview?.rows.filter(row=>row.cost_status==="READY")??[];const noChangesOverall=Boolean(preview&&preview.pagination.total>0&&Number(preview.batch.unchanged_rows??0)===preview.pagination.total);
  return <section className="space-y-4 rounded border border-black/10 p-4" aria-label="PDF Catalog Excel Round-trip">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="v14-eyebrow">Excel round-trip</p><h3 className="font-semibold">แก้หลายรายการด้วย Excel</h3><p className="text-xs text-black/55">ช่องว่าง = คงค่าเดิม · #CLEAR ใช้ได้เฉพาะข้อมูลสินค้าไม่บังคับ</p></div><div className="flex gap-2">{initialBatchId&&!preview?<button type="button" className="v14-button v14-button--outline" onClick={()=>openPreview(initialBatchId)}>เปิด Preview ล่าสุด</button>:null}<a className="v14-button v14-button--outline" href={`/api/admin/catalog/imports/${jobId}/enrichment/export`}><Download size={14}/>Export Excel</a></div></div>
    <div className="flex flex-wrap items-end gap-3"><label className="min-w-64 flex-1 text-sm">Upload Excel กลับ<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event=>setFile(event.target.files?.[0]??null)}/></label><button type="button" className="v14-button v14-button--dark" disabled={!file||!!busy} onClick={()=>void upload()}>{busy==="upload"?<LoaderCircle className="animate-spin" size={14}/>:<Upload size={14}/>}สร้าง Preview</button></div>
    {preview?<><div className="grid gap-2 sm:grid-cols-6">{[["พร้อมรายละเอียด",preview.batch.ready_detail_rows],["พร้อมต้นทุน",canReadCosts?preview.batch.ready_cost_rows:"—"],["ไม่เปลี่ยน",preview.batch.unchanged_rows],["ไม่ถูกต้อง",preview.batch.invalid_rows],["ข้อมูลเปลี่ยน",preview.batch.conflict_rows],["รอ Draft",canReadCosts?preview.batch.waiting_for_draft_rows:"—"]].map(([label,value])=><div key={String(label)} className="border border-black/10 p-2 text-xs"><span className="block text-black/50">{String(label)}</span><strong>{String(value??0)}</strong></div>)}</div>
      {noChangesOverall?<div role="status" className="rounded border border-[#b98a42]/40 bg-[#fff9ed] p-3 text-sm"><strong className="block">ไม่มีข้อมูลเปลี่ยนแปลง</strong><span>กรุณาแก้ไฟล์ Excel แล้วอัปโหลดอีกครั้ง</span></div>:null}
      <div className="max-h-[32rem] overflow-auto border border-black/10"><table className="w-full min-w-[980px] text-left text-xs"><thead className="sticky top-0 bg-[#f3f0e9]"><tr><th className="p-2">เลือก</th><th className="p-2">สินค้า</th><th className="p-2">สถานะรายละเอียด</th><th className="p-2">สถานะต้นทุน</th><th className="p-2">ข้อมูลที่เปลี่ยน</th><th className="p-2">ผลตรวจ</th></tr></thead><tbody>{preview.rows.map(row=>{const issue=enrichmentRowIssueLabel(row);const view=enrichmentPreviewView(row,canReadCosts);const price=canReadCosts&&row.cost_status==="APPLIED"?memberPricePreviewView(row.price_preview):null;const productId=row.applied_product_id??row.product_id??(String(row.price_preview?.productId??"")||null);return <tr key={row.id} className="border-t border-black/10 align-top"><td className="p-2">{row.detail_status==="READY"?<label><input aria-label={`เลือกรายละเอียด ${view.sku}`} type="checkbox" checked={checkedDetails.includes(row.id)} onChange={e=>setCheckedDetails(current=>e.target.checked?[...current,row.id]:current.filter(id=>id!==row.id))}/> รายละเอียด</label>:null}{canReadCosts&&row.cost_status==="READY"?<label className="mt-1 block"><input aria-label={`เลือกต้นทุน ${view.sku}`} type="checkbox" checked={checkedCosts.includes(row.id)} onChange={e=>setCheckedCosts(current=>e.target.checked?[...current,row.id]:current.filter(id=>id!==row.id))}/> ต้นทุน</label>:null}{row.detail_status!=="READY"&&(!canReadCosts||row.cost_status!=="READY")?<span className="text-black/40">—</span>:null}</td><td className="p-2"><strong className="block text-sm">{view.name}</strong><span className="text-black/55">SKU: {view.sku}</span></td><td className="p-2"><strong>{enrichmentStatusLabel(row.detail_status)}</strong></td><td className="p-2">{canReadCosts?<><strong>{enrichmentStatusLabel(row.cost_status)}</strong>{price?<div className="mt-2 rounded border border-[#b98a42]/40 bg-[#fff9ed] p-2"><span className="block text-black/55">Calculated Member Price Preview</span><strong className="block text-sm">{price.amountText} {price.currency}</strong><span className="font-semibold text-[#a83226]">{price.statusText}</span>{productId?<Link className="mt-1 block underline" href={`/admin/catalog?productId=${encodeURIComponent(productId)}&tab=pricing#pricing`}>ไป Pricing Workflow เดิม</Link>:null}</div>:null}</>:"ไม่มีสิทธิ์ดู"}</td><td className="min-w-[460px] space-y-3 p-2">{view.unchanged?<span className="font-medium text-black/55">ไม่มีข้อมูลเปลี่ยนแปลง</span>:<><ChangeTable title="รายละเอียดสินค้า" changes={view.detailChanges}/>{canReadCosts?<ChangeTable title="ต้นทุน" changes={view.costChanges}/>:null}</>}</td><td className="p-2">{issue?<span className="inline-flex items-start gap-1 text-[#a83226]"><AlertTriangle className="mt-0.5 shrink-0" size={13}/>{issue}</span>:<span className="inline-flex items-center gap-1 text-[#356b52]"><Check size={13}/>{view.unchanged?"ไม่ต้องยืนยัน":"พร้อม"}</span>}</td></tr>})}</tbody></table></div>
      <div className="flex flex-wrap gap-2"><button type="button" className="v14-button v14-button--dark" disabled={noChangesOverall||!canManage||!checkedDetails.length||!!busy} onClick={()=>void apply("details",checkedDetails)}>ยืนยันรายละเอียดสินค้า ({checkedDetails.length}/{readyDetails.length})</button>{canReadCosts?<button type="button" className="v14-button v14-button--dark" disabled={noChangesOverall||!canManageCosts||!checkedCosts.length||!!busy} onClick={()=>void apply("costs",checkedCosts)}>ยืนยันต้นทุน ({checkedCosts.length}/{readyCosts.length})</button>:null}<button type="button" className="v14-button v14-button--outline" disabled={!!busy} onClick={()=>void cancel()}><X size={14}/>ยกเลิกส่วนที่ยังไม่ Apply</button></div>
      {canReadCosts?<p className="text-xs text-black/55">ราคาสมาชิกด้านล่างเป็นเพียง Preview เท่านั้น ต้องไป Activate ในหน้าจอ Pricing ตามขั้นตอนเดิม</p>:null}
      {preview.pagination.totalPages>1?<div className="flex justify-end gap-2"><button type="button" disabled={preview.pagination.page<=1} onClick={()=>openPreview(String(preview.batch.id),preview.pagination.page-1)}>ก่อนหน้า</button><span>{preview.pagination.page}/{preview.pagination.totalPages}</span><button type="button" disabled={preview.pagination.page>=preview.pagination.totalPages} onClick={()=>openPreview(String(preview.batch.id),preview.pagination.page+1)}>ถัดไป</button></div>:null}</>:null}
  </section>;
}
