import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe,expect,it } from "vitest";
import { enrichmentPreviewView,enrichmentRowIssueLabel,enrichmentStatusLabel,formatEnrichmentPreviewValue,memberPricePreviewView,type PreviewRow } from "./catalog-enrichment-panel";
const ui=readFileSync(join(process.cwd(),"src/components/catalog-enrichment-panel.tsx"),"utf8");
const page=readFileSync(join(process.cwd(),"src/app/admin/catalog/imports/page.tsx"),"utf8");
const row=(overrides:Partial<PreviewRow>={}):PreviewRow=>({id:"row-1",row_key:"secret-row-key",product_id:"secret-product-id",detail_status:"UNCHANGED",cost_status:"UNCHANGED",baseline_detail:{sku:"SKU-01",name_th:"เก้าอี้",name_en:"Chair",factory_sku:null},proposed_detail:{},detail_diff:{},baseline_cost:{factory_cost:100,currency:"CNY",exchange_rate_to_thb:5},proposed_cost:null,cost_diff:{},price_preview:null,error_codes:[],warning_codes:[],...overrides});
describe("Catalog enrichment UI contract",()=>{
  it("shows the human-readable preview structure without raw JSON",()=>{for(const text of ["Export Excel","Upload Excel กลับ","ยืนยันรายละเอียดสินค้า","ยืนยันต้นทุน","Calculated Member Price Preview","ยังไม่เปิดใช้ราคา","ไป Pricing Workflow เดิม","ชื่อฟิลด์","ค่าเดิม","ค่าใหม่","ไม่มีข้อมูลเปลี่ยนแปลง","กรุณาแก้ไฟล์ Excel แล้วอัปโหลดอีกครั้ง","pagination.totalPages"])expect(ui).toContain(text);expect(ui).not.toContain("<pre");expect(ui).not.toContain("JSON.stringify({ก่อน");expect(ui).not.toContain('Number(preview.batch.invalid_rows??0)+Number(preview.batch.conflict_rows??0)');});
  it("identifies an unchanged product and exposes no selectable changes",()=>{expect(enrichmentPreviewView(row())).toEqual({sku:"SKU-01",name:"เก้าอี้",detailChanges:[],costChanges:[],unchanged:true});expect(ui).toContain('row.detail_status==="READY"?');expect(ui).toContain('row.cost_status==="READY"?');});
  it("renders only changed product fields with Thai labels and blank markers",()=>{const view=enrichmentPreviewView(row({detail_status:"READY",detail_diff:{name_th:"เก้าอี้ใหม่",factory_sku:null,product_id:"must-not-render",baseline_detail_hash:"must-not-render"}}));expect(view.detailChanges).toEqual([{field:"factory_sku",label:"รหัสโรงงาน",before:"—",after:"—"},{field:"name_th",label:"ชื่อสินค้า (ไทย)",before:"เก้าอี้",after:"เก้าอี้ใหม่"}].filter(change=>change.before!==change.after));expect(JSON.stringify(view)).not.toMatch(/must-not-render|product_id|hash|secret-row-key/);});
  it("renders changed costs only for users allowed to read costs",()=>{const changed=row({cost_status:"READY",proposed_cost:{factory_cost:125,currency:"THB",exchange_rate_to_thb:1},cost_diff:{factory_cost:125,currency:"THB",exchange_rate_to_thb:1,product_id:"must-not-render"}});expect(enrichmentPreviewView(changed).costChanges).toEqual([{field:"factory_cost",label:"ต้นทุนโรงงาน",before:"100",after:"125"},{field:"currency",label:"สกุลเงิน",before:"CNY",after:"THB"},{field:"exchange_rate_to_thb",label:"อัตราแลกเปลี่ยนเป็นบาท",before:"5",after:"1"}]);expect(enrichmentPreviewView(changed,false).costChanges).toEqual([]);});
  it("keeps conflict and error visibility in readable labels",()=>{expect(enrichmentRowIssueLabel({detail_status:"CONFLICT",cost_status:"UNCHANGED",error_codes:[]})).toBe("ข้อมูลต้นฉบับเปลี่ยน");expect(enrichmentRowIssueLabel({detail_status:"INVALID",cost_status:"UNCHANGED",error_codes:["DUPLICATE_SKU_IN_DATABASE"]})).toBe("SKU ซ้ำกับสินค้าเดิม");expect(enrichmentStatusLabel("INVALID")).toBe("ไม่ถูกต้อง");expect(formatEnrichmentPreviewValue(null,"name_en")).toBe("—");});
  it("formats an actual applied price preview amount, currency and inactive status",()=>{expect(memberPricePreviewView({memberPrice:"1234.5"})).toEqual({amountText:"1,234.50",currency:"THB",statusText:"ยังไม่เปิดใช้ราคา"});expect(memberPricePreviewView({})).toBeNull();expect(memberPricePreviewView({memberPrice:null})).toBeNull();expect(ui).toContain('canReadCosts&&row.cost_status==="APPLIED"');});
  it("passes independent cost permissions and feature flag",()=>{expect(page).toContain('catalog.cost.read');expect(page).toContain('catalog.cost.manage');expect(page).toContain('isCatalogExcelRoundtripEnabled()');});
});
