"use client";

import { BadgeCheck, Boxes, CalendarClock, CircleDollarSign, MapPin, PackageCheck, Ship, Truck, Upload } from "lucide-react";
import { useState } from "react";
import { allAdminOrderCapabilities } from "@/lib/orders/admin-access";
import { formatOrderMoney, type AdminOrderCapabilities, type OrderDetail, type Shipment } from "@/lib/orders/types";

type Post = (path:string,payload:Record<string,unknown>)=>Promise<boolean>;
const trackingOptions=["DEPARTED_CHINA","IN_TRANSIT","ARRIVED_THAILAND","IMPORT_CUSTOMS","THAILAND_WAREHOUSE","READY_FOR_DELIVERY"] as const;
const trackingLabels:Record<string,string>={DEPARTED_CHINA:"ออกจากจีน",IN_TRANSIT:"อยู่ระหว่างขนส่ง",ARRIVED_THAILAND:"ถึงประเทศไทย",IMPORT_CUSTOMS:"พิธีการศุลกากร",THAILAND_WAREHOUSE:"ถึงคลังไทย",READY_FOR_DELIVERY:"พร้อมนัดส่ง",DELAY:"ล่าช้า"};
const shipmentLabels:Record<string,string>={AWAITING_MEMBER_ACKNOWLEDGEMENT:"รอสมาชิกรับทราบค่าใช้จ่าย",GATE_CHECKED:"ผ่านเงื่อนไขก่อนจัดส่ง",DISPATCHED:"ออกเดินทางแล้ว",IN_TRANSIT:"อยู่ระหว่างขนส่ง",ARRIVED_THAILAND:"ถึงประเทศไทย",IMPORT_CUSTOMS:"ผ่านพิธีการนำเข้า",THAILAND_WAREHOUSE:"ถึงคลังไทย",READY_FOR_DELIVERY:"พร้อมนัดส่ง",PARTIALLY_DELIVERED:"ส่งมอบบางส่วน",DELIVERED:"ส่งมอบครบแล้ว"};
const deliveryLabels:Record<string,string>={PROPOSED:"รอสมาชิกยืนยันนัด",MEMBER_CONFIRMED:"สมาชิกยืนยันแล้ว",RESCHEDULE_REQUESTED:"ขอเลื่อนนัด",CONFIRMED:"ยืนยันนัดแล้ว",OUT_FOR_DELIVERY:"กำลังนำส่ง",ARRIVED:"ถึงหน้างาน",PARTIALLY_DELIVERED:"ส่งบางส่วน",DELIVERED:"ส่งครบ",DELIVERED_WITH_ISSUE:"ส่งพร้อมปัญหา",FAILED:"ส่งไม่สำเร็จ"};
const receiptLabels:Record<string,string>={DRAFT:"ฉบับร่าง",RECEIVED:"รับเข้าคลังแล้ว",QC_HOLD:"พักตรวจคุณภาพ",READY_FOR_CONSOLIDATION:"พร้อมรวมสินค้า",PARTIALLY_RELEASED:"ปล่อยบางส่วน",RELEASED:"ปล่อยครบแล้ว"};
const consolidationLabels:Record<string,string>={DRAFT:"ฉบับร่าง",CONFIRMED:"ยืนยันแล้ว",PACKING:"กำลังบรรจุ",READY_TO_SHIP:"พร้อมจัดส่ง",SHIPPED:"จัดส่งแล้ว",CANCELLED:"ยกเลิก"};
const consolidationStrategyLabels:Record<string,string>={CONSOLIDATE_ALL:"รวมทั้งหมด",PARTIAL:"ส่งบางส่วน",DIRECT:"ส่งตรง"};
const shipmentTypeLabels:Record<string,string>={CONSOLIDATED:"รวมเที่ยว",PARTIAL:"ส่งบางส่วน",DIRECT:"ส่งตรง"};
const conditionLabels:Record<string,string>={GOOD:"สภาพดี",DAMAGED:"ชำรุด",MISSING:"สูญหาย",WRONG_ITEM:"สินค้าผิดรายการ",OTHER:"อื่น ๆ"};
const costStatusLabels:Record<string,string>={DRAFT:"ฉบับร่าง",FINALIZED:"ยืนยันแล้ว",INVOICED:"ออกใบแจ้งหนี้แล้ว",VOID:"ยกเลิก"};
const invoiceStatusLabels:Record<string,string>={DRAFT:"ฉบับร่าง",ISSUED:"ออกใบแจ้งหนี้แล้ว",PARTIALLY_PAID:"ชำระบางส่วน",PAID:"ชำระแล้ว",VOID:"ยกเลิก"};
const iso=(days=0)=>new Date(Date.now()+days*86400000).toISOString();
const shipmentName=(name:string,orderNumber:string)=>name.startsWith("Shipment ")?`การจัดส่ง ${name.slice("Shipment ".length)}`:(name||`การจัดส่ง ${orderNumber}`);

function Status({children}:{children:string}){return <span className="v14-status v14-status--info">{children}</span>}

export function AdminLogisticsPanel({data,busy,post,capabilities=allAdminOrderCapabilities}:{data:OrderDetail;busy:boolean;post:Post;capabilities?:AdminOrderCapabilities}){
  const {logistics,order}=data;
  const [uploading,setUploading]=useState(false);
  async function uploadPod(deliveryId:string,file:File){
    setUploading(true);
    try{const form=new FormData();form.set("file",file);form.set("kind","DELIVERY_EVIDENCE");form.set("entityId",deliveryId);
      const response=await fetch("/api/admin/operations-media",{method:"POST",body:form});
      const body=await response.json() as {data?:{id:string};message?:string};
      if(!response.ok||!body.data?.id)throw new Error(body.message??"อัปโหลด POD ไม่สำเร็จ");return body.data.id;
    }finally{setUploading(false)}
  }
  async function submitPod(event:React.FormEvent<HTMLFormElement>,shipment:Shipment,deliveryId:string){
    event.preventDefault();const form=new FormData(event.currentTarget);const file=form.get("proof");
    if(!(file instanceof File)||!file.size)return;
    try{const fileId=await uploadPod(deliveryId,file);const delivery=shipment.deliveries.find(row=>row.id===deliveryId)!;
      await post("/api/admin/logistics/actions",{action:"RECORD_DELIVERY",delivery_id:deliveryId,delivered_at:new Date().toISOString(),recipient_name:form.get("recipient"),recipient_phone:form.get("phone"),items:delivery.items.map(item=>({shipment_item_id:item.shipment_item_id,quantity_delivered:Number(form.get(`qty-${item.id}`)),condition:form.get(`condition-${item.id}`),issue_type:form.get(`condition-${item.id}`)==="GOOD"?undefined:"OTHER",issue_description:form.get(`condition-${item.id}`)==="GOOD"?undefined:String(form.get("note")||"พบปัญหาขณะส่งมอบ")})),evidence_file_ids:[fileId],next_delivery_plan:form.get("nextPlan")||undefined,note:form.get("note")||undefined});
    }catch(error){window.alert(error instanceof Error?error.message:"บันทึก POD ไม่สำเร็จ")}
  }
  return <section className="slice8-stack">
    {capabilities.manageLogistics ? <><article className="v14-panel"><div className="v14-panel__head"><div><p className="v14-eyebrow">Slice 8 · การดำเนินงานภายใน</p><h2>รับเข้าคลังและรวมสินค้า</h2></div><Boxes/></div>
      <div className="slice8-grid">{logistics.receipts.map(receipt=><div className="slice8-card" key={receipt.id}><header><b>{receipt.receipt_number}</b><Status>{receiptLabels[receipt.status]??receipt.status}</Status></header><p>{new Date(receipt.received_at).toLocaleString("th-TH")} · {receipt.package_count} หีบห่อ · {receipt.actual_weight_kg??"—"} กก.</p>{receipt.items.map(item=><small key={item.id}>รับ {item.received_quantity} · ปล่อย {item.released_quantity} · พักไว้ {item.blocked_quantity}</small>)}</div>)}{!logistics.receipts.length?<p className="v14-empty">ยังไม่มีรายการรับเข้าคลัง</p>:null}</div>
      <div className="slice8-grid">{logistics.consolidations.map(group=><div className="slice8-card" key={group.id}><header><b>{group.consolidation_number}</b><Status>{consolidationLabels[group.status]??group.status}</Status></header><p>{consolidationStrategyLabels[group.strategy]??group.strategy} · {group.reason??"รวมสินค้าทั้งหมด"}</p><small>{group.items.length} รายการ · {group.items.reduce((sum,item)=>sum+Number(item.quantity),0)} หน่วย</small>{group.status==="CONFIRMED"&&!logistics.shipments.some(s=>s.id)&&<button disabled={busy} className="v14-button v14-button--dark" onClick={()=>void post("/api/admin/logistics/actions",{action:"CREATE_SHIPMENT",consolidation_id:group.id,shipment_name:`การจัดส่ง ${order.order_number}`,shipping_method:"LCL",tracking_number:`GISP-${Date.now()}`,etd_at:iso(),eta_at:iso(14),remaining_plan:"จัดส่งตามแผนส่งบางส่วนที่อนุมัติ",additional_member_charge:500,charge_bearer:"MEMBER"})}><Ship size={14}/>สร้างการจัดส่งบางส่วนสำหรับ UAT</button>}</div>)}</div>
    </article>
    {logistics.shipments.map(shipment=><article className="v14-panel" key={shipment.id}><div className="v14-panel__head"><div><p className="v14-eyebrow">{shipment.shipment_number} · {shipmentTypeLabels[shipment.shipment_type]??shipment.shipment_type}</p><h2>{shipmentName(shipment.shipment_name,order.order_number)}</h2></div><Status>{shipmentLabels[shipment.status]??shipment.status}</Status></div>
      <div className="slice8-summary"><span><Ship/>เลขติดตาม <b>{shipment.tracking_number??"—"}</b></span><span><PackageCheck/>จำนวน <b>{shipment.items.reduce((sum,item)=>sum+Number(item.quantity),0)}</b></span><span><CalendarClock/>กำหนดถึงโดยประมาณ <b>{shipment.estimated_arrival_at?new Date(shipment.estimated_arrival_at).toLocaleDateString("th-TH"):"—"}</b></span></div>
      {shipment.partialDecision?<div className="slice8-notice"><b>การจัดส่งบางส่วน</b><span>{shipment.partialDecision.reason} · ค่าใช้จ่ายของสมาชิก {formatOrderMoney(shipment.partialDecision.additional_member_charge,order.currency)}</span><Status>{shipment.partialDecision.member_acknowledged_at?"รับทราบแล้ว":"รอรับทราบ"}</Status></div>:null}
      {shipment.status==="GATE_CHECKED"?<button disabled={busy} className="v14-button v14-button--dark" onClick={()=>void post("/api/admin/logistics/actions",{action:"DISPATCH_SHIPMENT",shipment_id:shipment.id})}><Truck size={14}/>ยืนยันออกเดินทาง</button>:null}
      {["DISPATCHED","IN_TRANSIT","ARRIVED_THAILAND","IMPORT_CUSTOMS","THAILAND_WAREHOUSE"].includes(shipment.status)?<form className="slice8-inline-form" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void post("/api/admin/logistics/actions",{action:"ADD_TRACKING",shipment_id:shipment.id,status:form.get("status"),event_at:new Date().toISOString(),location:form.get("location"),note:form.get("note"),member_visible:true})}}><label>สถานะถัดไป<select key={shipment.history.length} name="status" defaultValue={trackingOptions.find(option=>!shipment.history.some(h=>h.status===option))??"READY_FOR_DELIVERY"}>{trackingOptions.map(option=><option key={option} value={option}>{trackingLabels[option]}</option>)}</select></label><label>สถานที่<input name="location" defaultValue="ประเทศไทย"/></label><label>หมายเหตุ<input name="note" defaultValue="อัปเดตสำหรับสมาชิก"/></label><button disabled={busy} className="v14-button"><MapPin size={14}/>เพิ่มสถานะติดตาม</button></form>:null}
      <div className="slice8-timeline">{shipment.history.map(event=><div key={event.id}><span/><section><b>{trackingLabels[event.status]??event.status}</b><p>{event.location_text??"—"} · {event.note??""}</p><small>{new Date(event.event_at).toLocaleString("th-TH")}</small></section></div>)}</div>
      {["READY_FOR_DELIVERY","PARTIALLY_DELIVERED"].includes(shipment.status)&&!shipment.deliveries.some(d=>["PROPOSED","MEMBER_CONFIRMED","RESCHEDULE_REQUESTED","CONFIRMED","OUT_FOR_DELIVERY","ARRIVED"].includes(d.status))?<form className="slice8-inline-form" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void post("/api/admin/logistics/actions",{action:"SCHEDULE_DELIVERY",shipment_id:shipment.id,scheduled_at:iso(1),scheduled_window_end:new Date(Date.now()+86400000+3600000).toISOString(),contact_name:form.get("contact"),contact_phone:form.get("phone"),site_note:form.get("note")})}}><label>ผู้ติดต่อ<input name="contact" defaultValue="สมาชิก UAT" required/></label><label>โทรศัพท์<input name="phone" defaultValue="0800000000" required/></label><label>หมายเหตุหน้างาน<input name="note" defaultValue="โทรก่อนถึงหน้างาน"/></label><button disabled={busy} className="v14-button v14-button--dark"><CalendarClock size={14}/>เสนอนัดส่งพรุ่งนี้</button></form>:null}
      {shipment.deliveries.map(delivery=><div className="slice8-delivery" key={delivery.id}><header><b>{delivery.delivery_number}</b><Status>{deliveryLabels[delivery.status]??delivery.status}</Status></header><p>{delivery.scheduled_at?new Date(delivery.scheduled_at).toLocaleString("th-TH"):"ยังไม่ระบุวัน"} · {delivery.contact_name}</p>
        {delivery.reschedules.filter(r=>r.status==="SUBMITTED").map(request=><div className="slice8-notice" key={request.id}><span><b>ขอเลื่อนนัด:</b> {request.reason}</span><button disabled={busy} className="v14-button v14-button--small" onClick={()=>void post("/api/admin/logistics/actions",{action:"REVIEW_RESCHEDULE",request_id:request.id,approve:true,decision_note:"ยืนยันวันใหม่ตามคำขอ UAT",accepted_scheduled_at:iso(2),accepted_window_end:new Date(Date.now()+2*86400000+3600000).toISOString()})}>อนุมัติวันใหม่</button></div>)}
        {["MEMBER_CONFIRMED","CONFIRMED"].includes(delivery.status)?<button disabled={busy} className="v14-button" onClick={()=>void post("/api/admin/logistics/actions",{action:"ADVANCE_DELIVERY",delivery_id:delivery.id,target_status:"OUT_FOR_DELIVERY",driver_name:"พนักงานจัดส่ง UAT",driver_phone:"0811111111",vehicle_registration:"UAT-8"})}><Truck size={14}/>เริ่มนำส่ง</button>:null}
        {delivery.status==="OUT_FOR_DELIVERY"?<form className="slice8-pod" onSubmit={event=>void submitPod(event,shipment,delivery.id)}><h3>หลักฐานการส่งมอบ</h3>{delivery.items.map(item=><div key={item.id}><label>จำนวนส่งจริง<input name={`qty-${item.id}`} type="number" min="0" max={item.expected_quantity} step="0.001" defaultValue={item.expected_quantity}/></label><label>สภาพ<select name={`condition-${item.id}`}>{Object.entries(conditionLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>)}<label>ผู้รับ<input name="recipient" defaultValue="ผู้รับสินค้า UAT" required/></label><label>โทรศัพท์<input name="phone" defaultValue="0800000000"/></label><label>แผนส่งครั้งถัดไป (กรณีส่งบางส่วน)<input name="nextPlan" placeholder="เช่น นัดส่งส่วนที่เหลืออีก 2 วัน"/></label><label>หมายเหตุ<input name="note" defaultValue="ตรวจรับที่หน้างาน"/></label><label>หลักฐานรูปภาพ/PDF<input name="proof" type="file" accept=".jpg,.jpeg,.png,.pdf" required/></label><button disabled={busy||uploading} className="v14-button v14-button--dark"><Upload size={14}/>{uploading?"กำลังอัปโหลด…":"บันทึกหลักฐานส่งมอบ"}</button></form>:null}
        {delivery.items.some(item=>Number(item.quantity_delivered)>0)?<div className="slice8-items">{delivery.items.map(item=><small key={item.id}>ส่ง {item.quantity_delivered}/{item.expected_quantity} · เหลือ {item.remaining_quantity} · {item.condition}</small>)}</div>:null}
      </div>)}
    </article>)}</> : null}
    {capabilities.manageFreight && logistics.shipments.some(shipment=>shipment.deliveries.some(delivery=>["DELIVERED","PARTIALLY_DELIVERED","DELIVERED_WITH_ISSUE"].includes(delivery.status)))?<article className="v14-panel slice8-freight"><div className="v14-panel__head"><div><p className="v14-eyebrow">ต้นทุนภายใน → ใบแจ้งหนี้สมาชิก</p><h2>ค่าขนส่งจริง</h2></div><CircleDollarSign/></div>
      <div className="slice8-items">{logistics.costs.map(cost=><div key={cost.id}><span><b>{cost.description}</b><small>{cost.category} · {costStatusLabels[cost.status]??cost.status}</small></span><span>ต้นทุน {formatOrderMoney(cost.supplier_cost,cost.supplier_currency)}<br/>เรียกเก็บ {formatOrderMoney(cost.member_charge,cost.member_currency)}</span></div>)}</div>
      {!logistics.costs.length?<form className="slice8-inline-form" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);const lastShipment=logistics.shipments.at(-1);const lastDelivery=lastShipment?.deliveries.at(-1);void post("/api/admin/logistics/actions",{action:"ADD_COST",customer_order_id:order.id,shipment_id:lastShipment?.id,delivery_id:lastDelivery?.id,category:"INTERNATIONAL_FREIGHT",description:"ค่าขนส่งระหว่างประเทศ",supplier_cost:form.get("supplierCost"),supplier_currency:"THB",exchange_rate:1,member_charge:form.get("memberCharge"),is_billable:true,internal_note:"ข้อมูลต้นทุนภายใน",member_visible_note:"ค่าขนส่งตามจริง",evidence_file_ids:[]})}}><label>ต้นทุนภายใน<input name="supplierCost" type="number" defaultValue="8000"/></label><label>ยอดเรียกเก็บ Member<input name="memberCharge" type="number" defaultValue="10000"/></label><button disabled={busy} className="v14-button">บันทึก Actual Cost</button></form>:null}
      {logistics.costs.some(cost=>cost.status==="DRAFT")?<button disabled={busy} className="v14-button v14-button--dark" onClick={()=>void post("/api/admin/logistics/actions",{action:"FINALIZE_COSTS",customer_order_id:order.id})}><BadgeCheck size={14}/>ฝ่ายการเงินยืนยันต้นทุน</button>:null}
      {logistics.costs.some(cost=>cost.status==="FINALIZED")&&!logistics.invoice?<button disabled={busy} className="v14-button v14-button--dark" onClick={()=>void post("/api/admin/logistics/actions",{action:"ISSUE_INVOICE",customer_order_id:order.id,vat_rate:7,due_at:iso(7),note:"ใบแจ้งหนี้ค่าขนส่งจากต้นทุนจริง"})}>ออกใบแจ้งหนี้ค่าขนส่ง</button>:null}
      {logistics.invoice?<div className="slice8-invoice"><b>{logistics.invoice.invoice_number}</b><strong>{formatOrderMoney(logistics.invoice.grand_total,logistics.invoice.currency)}</strong><Status>{invoiceStatusLabels[logistics.invoice.status]??logistics.invoice.status}</Status></div>:null}
    </article>:null}
  </section>
}

export function MemberLogisticsPanel({data,busy,post}:{data:OrderDetail;busy:boolean;post:Post}){
  return <section className="slice8-stack"><article className="v14-panel"><div className="v14-panel__head"><div><p className="v14-eyebrow">การจัดส่งและการส่งมอบ</p><h2>ติดตามการจัดส่ง</h2></div><Truck/></div>{data.logistics.shipments.length?data.logistics.shipments.map(shipment=><div className="slice8-member-shipment" key={shipment.id}><header><span><b>{shipment.shipment_number}</b><small>เลขติดตาม {shipment.tracking_number??"—"}</small></span><Status>{shipmentLabels[shipment.status]??shipment.status}</Status></header>
    {shipment.partialDecision?<div className="slice8-notice"><span><b>{shipment.partialDecision.member_acknowledgement_required&&!shipment.partialDecision.member_acknowledged_at?"ต้องรับทราบก่อนจัดส่ง":"ข้อมูลการจัดส่งบางส่วน"}</b><br/>{shipment.partialDecision.reason} · ค่าใช้จ่ายเพิ่ม {formatOrderMoney(shipment.partialDecision.additional_member_charge,data.order.currency)}</span>{shipment.partialDecision.member_acknowledgement_required&&!shipment.partialDecision.member_acknowledged_at?<button disabled={busy} className="v14-button v14-button--dark" onClick={()=>void post("/api/member/logistics/actions",{action:"ACK_PARTIAL",shipment_id:shipment.id,note:"ตรวจรายละเอียดและรับทราบแล้ว"})}>รับทราบ</button>:<Status>{shipment.partialDecision.member_acknowledged_at?"รับทราบแล้ว":"ไม่ต้องรับทราบ"}</Status>}</div>:null}
    <div className="slice8-timeline">{shipment.history.map(event=><div key={event.id}><span/><section><b>{trackingLabels[event.status]??event.status}</b><p>{event.location_text??""} · {event.note??""}</p><small>{new Date(event.event_at).toLocaleString("th-TH")}</small></section></div>)}</div>
    {shipment.deliveries.map(delivery=><div className="slice8-delivery" key={delivery.id}><header><b>{delivery.delivery_number}</b><Status>{deliveryLabels[delivery.status]??delivery.status}</Status></header><p>{delivery.scheduled_at?new Date(delivery.scheduled_at).toLocaleString("th-TH"):"รอวันนัด"} · {delivery.contact_name}</p>{delivery.status==="PROPOSED"?<div className="v14-actions"><button disabled={busy} className="v14-button v14-button--dark" onClick={()=>void post("/api/member/logistics/actions",{action:"CONFIRM_APPOINTMENT",delivery_id:delivery.id})}>ยืนยันนัด</button><button disabled={busy} className="v14-button v14-button--outline" onClick={()=>void post("/api/member/logistics/actions",{action:"REQUEST_RESCHEDULE",delivery_id:delivery.id,preferred_dates:[iso(2)],reason:"ขอเลื่อนเพื่อเตรียมพื้นที่หน้างาน",contact_name:delivery.contact_name??undefined,contact_phone:delivery.contact_phone??undefined,site_note:"กรุณาโทรก่อนถึง"})}>ขอเลื่อน 2 วัน</button></div>:null}<div className="slice8-items">{delivery.items.map(item=><small key={item.id}>ส่งแล้ว {item.quantity_delivered}/{item.expected_quantity} · เหลือ {item.remaining_quantity} · {conditionLabels[item.condition]??item.condition}</small>)}</div>{delivery.evidence.length?<p>หลักฐานส่งมอบ: {delivery.evidence.map(item=><a key={item.id} href={`/api/files/${item.file_id}/download?redirect=1`} target="_blank" rel="noreferrer">ดูหลักฐาน</a>)}</p>:null}</div>)}
  </div>):<p className="v14-empty">ยังไม่มีรายการจัดส่ง — รอทีมขนส่งเตรียมการจัดส่ง</p>}</article>
  {data.logistics.invoice?<article className="v14-panel"><div className="v14-panel__head"><div><p className="v14-eyebrow">ใบแจ้งหนี้ค่าขนส่งจริง</p><h2>{data.logistics.invoice.invoice_number}</h2></div><Status>{invoiceStatusLabels[data.logistics.invoice.status]??data.logistics.invoice.status}</Status></div><div className="slice8-items">{data.logistics.invoice.items.map(item=><div key={item.id}><span><b>{item.description_snapshot}</b><small>{item.category_snapshot}</small></span><strong>{formatOrderMoney(item.amount_snapshot,data.logistics.invoice!.currency)}</strong></div>)}</div><div className="slice8-invoice"><span>รวมภาษีมูลค่าเพิ่ม {data.logistics.invoice.vat_rate_snapshot}%</span><strong>{formatOrderMoney(data.logistics.invoice.grand_total,data.logistics.invoice.currency)}</strong></div><p>ส่งหลักฐานการโอนได้จากกล่อง “ส่งหลักฐานการโอน” ด้านบน โดยเลือกงวดค่าขนส่ง</p></article>:null}</section>
}
