"use client";

import { ArrowLeft, CheckCircle2, ExternalLink, FileUp, RefreshCw, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { claimIssueLabels, claimStatusLabels, claimTone, resolutionLabels, responsibilityLabels, type ClaimDetail } from "@/lib/claims/types";

export function MemberClaimDetail({ claimId }: { claimId: string }) {
  const [data, setData] = useState<ClaimDetail>();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string>();
  const [message, setMessage] = useState<string>();
  const [showIssueForm, setShowIssueForm] = useState(false);
  const load = useCallback(async () => { const response = await fetch(`/api/member/claims/${claimId}`, { cache: "no-store" }); const body = await response.json() as { data?: ClaimDetail; message?: string }; if (!response.ok || !body.data) setError(body.message ?? "โหลด Claim ไม่สำเร็จ"); else setData(body.data); }, [claimId]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function action(payload: Record<string, unknown>) { setBusy(true); setError(undefined); setMessage(undefined); try { const response = await fetch(`/api/member/claims/${claimId}/actions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json() as { message?: string }; if (!response.ok) throw new Error(body.message ?? "อัปเดต Claim ไม่สำเร็จ"); setMessage(body.message); setShowIssueForm(false); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "อัปเดต Claim ไม่สำเร็จ"); } finally { setBusy(false); } }
  async function addInformation(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(undefined); const formElement = event.currentTarget; const form = new FormData(formElement); try { let evidenceId: string | undefined; const file = form.get("file"); if (file instanceof File && file.size) { const upload = new FormData(); upload.set("file", file); const response = await fetch("/api/claims/evidence", { method: "POST", body: upload }); const body = await response.json() as { data?: { id: string }; message?: string }; if (!response.ok || !body.data?.id) throw new Error(body.message ?? "อัปโหลดหลักฐานไม่สำเร็จ"); evidenceId = body.data.id; } await action({ action: "ADD_INFORMATION", note: form.get("note"), evidence_file_id: evidenceId }); formElement.reset(); } catch (caught) { setError(caught instanceof Error ? caught.message : "ส่งข้อมูลไม่สำเร็จ"); setBusy(false); } }
  if (!data) return <div className="v14-panel v14-empty">{error ?? "กำลังโหลด Claim…"}</div>;
  const { claim } = data; const warranty = claim.warranty_snapshot ?? {};
  return <main className="claim-detail"><Link href="/member/claims" className="member-detail__back"><ArrowLeft/>กลับรายการ Claim</Link><section className="quotation-detail__hero"><div><p className="v14-eyebrow">{claim.claim_number} · {claim.order_number}</p><h1>{claim.subject}</h1><p>{claim.item_name} · จำนวนที่แจ้ง {claim.claimed_quantity}</p></div><span className={`v14-status v14-status--${claimTone(claim.status)}`}><small>สถานะปัจจุบัน</small>{claimStatusLabels[claim.status] ?? claim.status}</span></section>{error ? <p className="v14-alert">{error}</p> : null}{message ? <p className="quotation-success">{message}</p> : null}
    {claim.information_request ? <section className="claim-action-banner"><b>ทีมงานขอข้อมูลเพิ่มเติม</b><span>{claim.information_request}</span></section> : null}
    <section className="claim-detail__grid"><article className="v14-panel"><p className="v14-eyebrow">รายละเอียดปัญหา</p><h2>{claimIssueLabels[claim.issue_type] ?? claim.issue_type}</h2><p className="claim-description">{claim.description}</p><dl className="claim-facts"><div><dt>ความเร่งด่วน</dt><dd>{claim.severity}</dd></div><div><dt>วันที่พบ</dt><dd>{new Date(claim.discovered_at).toLocaleString("th-TH")}</dd></div><div><dt>สภาพบรรจุภัณฑ์</dt><dd>{claim.packaging_condition ?? "ไม่ได้ระบุ"}</dd></div><div><dt>การแก้ไขชั่วคราว</dt><dd>{claim.temporary_action ?? "ไม่ได้ระบุ"}</dd></div></dl></article><aside><article className="v14-panel claim-warranty"><div className="v14-panel__head"><div><p className="v14-eyebrow">Warranty Snapshot</p><h2>{String(warranty.title ?? "เงื่อนไขรับประกัน")}</h2></div><ShieldCheck/></div><p>{String(warranty.member_summary ?? "ทีมงานจะตรวจสอบตามเงื่อนไข ณ วันที่เปิด Claim")}</p><small>Snapshot เวอร์ชัน {String(warranty.version_number ?? "—")} · ไม่เปลี่ยนตามข้อมูลภายหลัง</small></article><article className="v14-panel"><p className="v14-eyebrow">Responsibility</p><h2>ผู้รับผิดชอบ</h2><dl className="claim-facts"><div><dt>ระบบแนะนำ</dt><dd>{responsibilityLabels[claim.suggested_responsibility] ?? claim.suggested_responsibility}</dd></div><div><dt>Order Admin ยืนยัน</dt><dd>{claim.confirmed_responsibility ? responsibilityLabels[claim.confirmed_responsibility] : "รอการยืนยัน"}</dd></div></dl><small>ข้อมูลนี้ไม่ใช่การอนุมัติชดเชยอัตโนมัติ</small></article></aside></section>
    {claim.resolution_type ? <section className="v14-panel claim-resolution"><div className="v14-panel__head"><div><p className="v14-eyebrow">Resolution</p><h2>{resolutionLabels[claim.resolution_type] ?? claim.resolution_type}</h2></div>{claim.resolution_executed_at ? <CheckCircle2/> : null}</div><p>{claim.resolution_details}</p>{claim.status === "RESOLVED" && !claim.member_confirmed_at ? <><div className="v14-actions"><button disabled={busy} onClick={() => void action({ action: "CONFIRM_RESOLVED", note: "ตรวจรับผลแก้ไขแล้ว" })} className="v14-button v14-button--dark">ยืนยันว่าแก้ไขแล้ว</button><button disabled={busy} onClick={() => setShowIssueForm(!showIssueForm)} className="v14-button v14-button--outline">ยังมีปัญหา</button><button disabled={busy} onClick={() => void action({ action: "CONTACT_ME", note: "กรุณาติดต่อกลับ" })} className="v14-button v14-button--outline">ขอให้ติดต่อกลับ</button></div>{showIssueForm ? <form className="claim-decision-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void action({ action: "STILL_ISSUE", note: form.get("note") }); }}><label>โปรดระบุปัญหาที่ยังพบ<textarea name="note" rows={3} minLength={3} autoFocus required placeholder="อธิบายอาการหรือปัญหาที่ยังพบ"/></label><div className="v14-actions"><button disabled={busy} className="v14-button v14-button--dark">ยืนยันและส่งข้อมูล</button><button type="button" disabled={busy} onClick={() => setShowIssueForm(false)} className="v14-button v14-button--outline">ยกเลิก</button></div></form> : null}</> : null}{claim.member_confirmed_at ? <p className="quotation-success">คุณยืนยันผลแก้ไขเมื่อ {new Date(claim.member_confirmed_at).toLocaleString("th-TH")}</p> : null}</section> : null}
    {claim.status === "WAITING_INFORMATION" ? <section className="v14-panel"><div className="v14-panel__head"><div><p className="v14-eyebrow">Action required</p><h2>ส่งข้อมูลเพิ่มเติม</h2></div><FileUp/></div><form className="claim-inline-form" onSubmit={addInformation}><textarea name="note" rows={3} placeholder="อธิบายข้อมูลเพิ่มเติม"/><input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png,.mp4"/><button disabled={busy} className="v14-button v14-button--dark">ส่งให้ทีมตรวจสอบ</button></form></section> : null}
    <section className="claim-detail__grid"><article className="v14-panel"><div className="v14-panel__head"><div><p className="v14-eyebrow">Evidence</p><h2>หลักฐาน</h2></div></div><div className="claim-files">{data.evidence.map((item) => <a key={item.id} href={`/api/claims/evidence/${item.file_id}?redirect=1`} target="_blank" rel="noreferrer"><FileUp/><span><b>{item.file?.original_name ?? "ไฟล์หลักฐาน"}</b><small>{item.evidence_type} · {new Date(item.created_at).toLocaleString("th-TH")}</small></span><ExternalLink/></a>)}</div></article><article className="v14-panel"><div className="v14-panel__head"><div><p className="v14-eyebrow">Timeline</p><h2>ประวัติ Claim</h2></div><button onClick={() => void load()} className="v14-button v14-button--outline v14-button--small"><RefreshCw size={14}/>โหลดใหม่</button></div><div className="quotation-timeline">{data.events.map((event) => <article key={event.id}><span/><div><b>{claimStatusLabels[event.action] ?? event.action.replaceAll("_", " ")}</b><p>{event.note ?? "อัปเดต Claim"}</p><small>{new Date(event.created_at).toLocaleString("th-TH")}</small></div></article>)}</div></article></section>
  </main>;
}
