"use client";

import { ArrowLeft, ArrowRight, Check, LoaderCircle } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { BUSINESS_TYPE_OPTIONS, businessTypeDraftFromStored, type BusinessTypeSelection } from "@/lib/member/business-types";

type InitialProfile = Partial<Record<string, string | string[] | boolean>>;

export function OnboardingForm({ defaultName, initial = {} }: { defaultName?: string; initial?: InitialProfile }) {
  const initialBusinessType = businessTypeDraftFromStored(String(initial.business_type ?? ""));
  const router=useRouter(); const [step,setStep]=useState(1); const [pending,setPending]=useState(false); const [error,setError]=useState<string>();
  const [businessType,setBusinessType]=useState<BusinessTypeSelection>(initialBusinessType.code);
  async function submit(formData:FormData){setPending(true);setError(undefined);const raw=Object.fromEntries(formData.entries());const payload={...raw,service_areas:String(raw.service_areas??"").split(",").map(v=>v.trim()).filter(Boolean),product_interests:String(raw.product_interests??"").split(",").map(v=>v.trim()).filter(Boolean),training_interest:raw.training_interest==="on",consents:{terms:raw.terms==="on",privacy:raw.privacy==="on"}};try{const response=await fetch("/api/member/onboarding",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json() as {message?:string};if(!response.ok)throw new Error(body.message??"ส่งข้อมูลไม่สำเร็จ");router.replace("/pending-approval");router.refresh()}catch(caught){setError(caught instanceof Error?caught.message:"เกิดข้อผิดพลาด")}finally{setPending(false)}}
  return <form action={submit} className="mt-8">
    <div className="mb-7 grid grid-cols-3 gap-2">{["ผู้ติดต่อ","บริษัท","ตรวจทาน"].map((label,index)=><div key={label} className={`rounded-xl border px-3 py-2 text-center text-[10px] font-bold ${step===index+1?"border-lacquer bg-lacquer text-white":"border-ink/10 bg-white text-ink/45"}`}>{index+1}. {label}</div>)}</div>
    <div className={step===1?"grid gap-4":"hidden"}><Field name="contact_name" label="ชื่อผู้ติดต่อ" defaultValue={String(initial.contact_name??defaultName??"")}/><Field name="contact_phone" label="เบอร์โทรศัพท์" defaultValue={String(initial.contact_phone??"")}/><Field name="company_name" label="ชื่อบริษัท / สตูดิโอ" defaultValue={String(initial.company_name??"")}/><Field name="company_legal_name" label="ชื่อนิติบุคคล" defaultValue={String(initial.company_legal_name??"")}/><Field name="tax_id" label="เลขประจำตัวผู้เสียภาษี" defaultValue={String(initial.tax_id??"")}/></div>
    <div className={step===2?"grid gap-4":"hidden"}>
      <label className="block"><span className="mb-1.5 block text-xs font-bold text-ink/55">ประเภทธุรกิจ</span><select name="business_type" required value={businessType} onChange={(event)=>setBusinessType(event.target.value as BusinessTypeSelection)} className="h-12 w-full rounded-xl border border-ink/10 bg-white px-4 text-sm outline-none focus:border-lacquer/45 focus:ring-4 focus:ring-lacquer/8"><option value="" disabled>เลือกประเภทธุรกิจ</option>{BUSINESS_TYPE_OPTIONS.map((option)=><option key={option.code} value={option.code}>{option.label}</option>)}</select></label>
      {businessType==="OTHER"&&<Field name="business_type_other" label="ระบุประเภทธุรกิจอื่น ๆ" required defaultValue={initialBusinessType.other}/>}<Field name="address_line" label="ที่อยู่" defaultValue={String(initial.address_line??"")}/><div className="grid gap-4 sm:grid-cols-3"><Field name="district" label="เขต / อำเภอ" defaultValue={String(initial.district??"")}/><Field name="province" label="จังหวัด" defaultValue={String(initial.province??"")}/><Field name="postal_code" label="รหัสไปรษณีย์" defaultValue={String(initial.postal_code??"")}/></div><Field name="service_areas" label="พื้นที่ให้บริการ (คั่นด้วยจุลภาค)" defaultValue={Array.isArray(initial.service_areas)?initial.service_areas.join(", "):String(initial.service_areas??"")}/><Field name="product_interests" label="สินค้าที่สนใจ (คั่นด้วยจุลภาค)" defaultValue={Array.isArray(initial.product_interests)?initial.product_interests.join(", "):String(initial.product_interests??"")}/></div>
    <div className={step===3?"grid gap-4":"hidden"}><label className="flex items-start gap-3 rounded-xl border border-ink/10 bg-white p-4 text-sm"><input name="training_interest" type="checkbox" defaultChecked={Boolean(initial.training_interest)} className="mt-1"/>สนใจหลักสูตร / การอบรมจาก GISP</label><Field name="training_note" label="หัวข้อหลักสูตรที่สนใจ" defaultValue={String(initial.training_note??"")}/><label className="flex items-start gap-3 text-xs leading-5"><input name="terms" type="checkbox" required className="mt-1"/>ยอมรับเงื่อนไขการใช้งานเวอร์ชัน 2026-08-18</label><label className="flex items-start gap-3 text-xs leading-5"><input name="privacy" type="checkbox" required className="mt-1"/>รับทราบนโยบายความเป็นส่วนตัวเวอร์ชัน 2026-08-18</label><div className="rounded-2xl bg-jade/10 p-4 text-xs leading-6 text-jade"><Check size={17} className="mb-2"/>เมื่อส่งแล้ว สถานะจะเป็น Pending และทีม GISP จะตรวจข้อมูลก่อนเปิดสิทธิ์ Member</div></div>
    {error&&<p role="alert" className="mt-4 rounded-xl bg-lacquer/10 px-4 py-3 text-xs text-lacquer">{error}</p>}
    <div className="mt-6 flex gap-3">{step>1&&<button type="button" onClick={()=>setStep(v=>v-1)} className="inline-flex h-12 items-center gap-2 rounded-xl border border-ink/15 px-5 text-sm font-bold"><ArrowLeft size={16}/>ย้อนกลับ</button>}{step<3?<button type="button" onClick={()=>setStep(v=>v+1)} className="ml-auto inline-flex h-12 items-center gap-2 rounded-xl bg-ink px-6 text-sm font-bold text-white">ถัดไป<ArrowRight size={16}/></button>:<button type="submit" disabled={pending} className="ml-auto inline-flex h-12 items-center gap-2 rounded-xl bg-lacquer px-6 text-sm font-bold text-white disabled:opacity-60">{pending?<LoaderCircle size={16} className="animate-spin"/>:<Check size={16}/>}ส่งคำขออนุมัติ</button>}</div>
  </form>;
}

function Field({label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className="block"><span className="mb-1.5 block text-xs font-bold text-ink/55">{label}</span><input {...props} required={["contact_name","company_name"].includes(String(props.name))} className="h-12 w-full rounded-xl border border-ink/10 bg-white px-4 text-sm outline-none focus:border-lacquer/45 focus:ring-4 focus:ring-lacquer/8"/></label>}
