import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe,expect,it } from "vitest";
const read=(path:string)=>readFileSync(join(process.cwd(),path),"utf8");
const routes={export:read("src/app/api/admin/catalog/imports/[id]/enrichment/export/route.ts"),upload:read("src/app/api/admin/catalog/imports/[id]/enrichment/uploads/route.ts"),preview:read("src/app/api/admin/catalog/imports/[id]/enrichment/[batchId]/route.ts"),details:read("src/app/api/admin/catalog/imports/[id]/enrichment/[batchId]/apply-details/route.ts"),costs:read("src/app/api/admin/catalog/imports/[id]/enrichment/[batchId]/apply-costs/route.ts"),cancel:read("src/app/api/admin/catalog/imports/[id]/enrichment/[batchId]/cancel/route.ts")};
const service=read("src/lib/catalog/enrichment-service.ts");
describe("Catalog enrichment API contract",()=>{
  it("gates every endpoint with the default-off feature flag",()=>{for(const source of Object.values(routes))expect(source).toContain("isCatalogExcelRoundtripEnabled")});
  it("uses the approved permission split",()=>{expect(routes.export).toContain('permissions:["catalog.import"]');expect(routes.upload).toContain('permissions:["catalog.import"]');expect(routes.preview).toContain('permissions:["catalog.import"]');expect(routes.details).toContain('permissions:["catalog.import","catalog.manage"]');expect(routes.costs).toContain('permissions:["catalog.import","catalog.cost.manage"]');expect(routes.cancel).toContain('permissions:["catalog.import"]');});
  it("validates URL IDs, input schemas and cross-job batch linkage",()=>{for(const source of Object.values(routes))expect(source).toContain("z.uuid()");expect(routes.details).toContain("enrichmentApplySchema.safeParse");expect(routes.costs).toContain("enrichmentApplySchema.safeParse");expect(routes.cancel).toContain("enrichmentCancelSchema.safeParse");for(const source of [routes.details,routes.costs,routes.cancel])expect(source).toContain("ensureEnrichmentBatchJob(id,batchId)");});
  it("redacts cost data unless catalog.cost.read",()=>{expect(routes.preview).toContain('context.permissions.includes("catalog.cost.read")');});
  it("uses a deterministic two-column order across 1,000-row page boundaries",()=>{expect(service).toContain('.order("row_number",{ascending:true}).order("id",{ascending:true})');const rows=Array.from({length:1000},(_,index)=>({id:String(999-index).padStart(4,"0"),row_number:Math.floor(index/2)+1,created_at:"2026-09-13T00:00:00Z"})).sort((left,right)=>left.row_number-right.row_number||left.id.localeCompare(right.id));const pages=Array.from({length:20},(_,page)=>rows.slice(page*50,page*50+50));const ids=pages.flat().map(row=>row.id);expect(ids).toHaveLength(1000);expect(new Set(ids).size).toBe(1000);expect(ids).toEqual(rows.map(row=>row.id));});
  it("loads the export filename through source_file_id instead of a nonexistent job column",()=>{expect(service).toContain('select("id,source_type,status,source_file_id")');expect(service).toContain('.from("file_metadata")');expect(service).toContain('select("id,original_name,bucket,visibility,entity_type,entity_id")');expect(service).not.toContain("job.file_name");expect(service).not.toContain('status,file_name');});
  it("constructs and URI-validates the response filename before persistent export writes",()=>{expect(service.indexOf("const filename = resolveCatalogEnrichmentFilename")).toBeGreaterThan(0);expect(service.indexOf("encodeURIComponent(filename)")).toBeGreaterThan(service.indexOf("const filename = resolveCatalogEnrichmentFilename"));expect(service.indexOf("const uploaded = await admin.storage")).toBeGreaterThan(service.indexOf("encodeURIComponent(filename)"));});
});
