import { beforeEach,describe,expect,it,vi } from "vitest";
vi.mock("server-only",()=>({}));
import { strToU8,unzipSync,zipSync } from "fflate";
import { buildCatalogEnrichmentWorkbook,parseCatalogEnrichmentWorkbook,validateCatalogEnrichmentArchive,type EnrichmentExportRow } from "./enrichment-xlsx";
import { CATALOG_EXCEL_MAX_BYTES,CATALOG_EXCEL_MIME,CATALOG_EXCEL_SCHEMA_VERSION,isCatalogExcelRoundtripEnabled,parseFactoryCost,parseOptionalNumber,resolveCatalogEnrichmentFilename,safeSpreadsheetText,stableHash,summarizeEnrichmentStatuses } from "./excel-roundtrip";

const row=(index=1):EnrichmentExportRow=>({rowKey:`00000000-0000-4000-8000-${String(index).padStart(12,"0")}`,importRowId:`10000000-0000-4000-8000-${String(index).padStart(12,"0")}`,productId:null,sourcePage:index,detail:{sku:`CN-${index}`,factory_sku:"工厂-01",name_th:"เก้าอี้",name_en:"Chair",name_zh:"椅子",product_type:"STANDARD",category_code:"CHAIR",country_code:"CN",lead_time_days:30,width_mm:500,depth_mm:500,height_mm:800,weight_kg:8,cbm:.2,material_summary:"ไม้",finish_summary:"ด้าน",moq:1,description_th:"=ข้อความ ไม่ใช่สูตร",specification_summary:"规格"},cost:null,baselineDetailHash:stableHash({sku:`CN-${index}`}),baselineCostHash:null});
function file(bytes:Uint8Array,name="roundtrip.xlsx",type=CATALOG_EXCEL_MIME){return new File([Buffer.from(bytes)],name,{type});}

describe("PDF Catalog Excel Round-trip workbook",()=>{
  beforeEach(()=>delete process.env.ENABLE_CATALOG_EXCEL_ROUNDTRIP);
  it("defaults the feature flag off",()=>{expect(isCatalogExcelRoundtripEnabled()).toBe(false);process.env.ENABLE_CATALOG_EXCEL_ROUNDTRIP="true";expect(isCatalogExcelRoundtripEnabled()).toBe(true);});
  it("creates and reads a valid five-sheet multilingual workbook",async()=>{const bytes=buildCatalogEnrichmentWorkbook({workbookId:"20000000-0000-4000-8000-000000000001",jobId:"30000000-0000-4000-8000-000000000001",exportedAt:"2026-09-13T00:00:00Z",rows:[row()],categories:["CHAIR"],countries:["CN","TH"],includeCosts:true});const parsed=await parseCatalogEnrichmentWorkbook(file(bytes));expect(parsed.productRows).toHaveLength(1);expect(parsed.productRows[0].name_zh).toBe("椅子");expect(parsed.productRows[0].description_th).toBe("=ข้อความ ไม่ใช่สูตร");expect(parsed.metaRows[0].schema_version).toBe(CATALOG_EXCEL_SCHEMA_VERSION);expect(parsed.costRows).toHaveLength(1);});
  it("supports the exact 1000-row limit within 30 seconds",async()=>{const started=Date.now();const rows=Array.from({length:1000},(_,index)=>row(index+1));const bytes=buildCatalogEnrichmentWorkbook({workbookId:"20000000-0000-4000-8000-000000000001",jobId:"30000000-0000-4000-8000-000000000001",exportedAt:"2026-09-13T00:00:00Z",rows,categories:["CHAIR"],countries:["CN"],includeCosts:false});const parsed=await parseCatalogEnrichmentWorkbook(file(bytes));expect(parsed.productRows).toHaveLength(1000);expect(parsed.costRows).toEqual([]);expect(Date.now()-started).toBeLessThan(30000);});
  it("rejects actual formula XML, macro/external parts and bad MIME",()=>{const bytes=buildCatalogEnrichmentWorkbook({workbookId:"20000000-0000-4000-8000-000000000001",jobId:"30000000-0000-4000-8000-000000000001",exportedAt:"2026-09-13T00:00:00Z",rows:[row()],categories:[],countries:["CN"],includeCosts:false});const entries=unzipSync(bytes);entries["xl/worksheets/sheet2.xml"]=strToU8('<?xml version="1.0"?><worksheet><sheetData><row><c><f>1+1</f></c></row></sheetData></worksheet>');expect(()=>validateCatalogEnrichmentArchive(file(zipSync(entries)),zipSync(entries))).toThrow(/สูตร/);expect(()=>validateCatalogEnrichmentArchive(file(bytes,"roundtrip.xlsm"),bytes)).toThrow();expect(()=>validateCatalogEnrichmentArchive(file(bytes,"roundtrip.xlsx","application/octet-stream"),bytes)).toThrow();});
  it("rejects active content, unsafe duplicate paths and excessive ZIP expansion",()=>{const bytes=buildCatalogEnrichmentWorkbook({workbookId:"20000000-0000-4000-8000-000000000001",jobId:"30000000-0000-4000-8000-000000000001",exportedAt:"2026-09-13T00:00:00Z",rows:[row()],categories:[],countries:["CN"],includeCosts:false});const macro={...unzipSync(bytes),"xl/vbaProject.bin":strToU8("unsafe")};const macroBytes=zipSync(macro);expect(()=>validateCatalogEnrichmentArchive(file(macroBytes),macroBytes)).toThrow(/Macro/);const external={...unzipSync(bytes),"xl/externalLinks/externalLink1.xml":strToU8("<externalLink/>")};const externalBytes=zipSync(external);expect(()=>validateCatalogEnrichmentArchive(file(externalBytes),externalBytes)).toThrow(/external/);const duplicate={...unzipSync(bytes),"XL/WORKBOOK.XML":strToU8("<workbook/>")};const duplicateBytes=zipSync(duplicate);expect(()=>validateCatalogEnrichmentArchive(file(duplicateBytes),duplicateBytes)).toThrow(/part ซ้ำ/);const bomb={...unzipSync(bytes),"xl/media/oversized.bin":new Uint8Array(2*1024*1024)};const bombBytes=zipSync(bomb,{level:9});expect(()=>validateCatalogEnrichmentArchive(file(bombBytes),bombBytes)).toThrow(/ขยายตัว/);});
  it("fails closed on encrypted flags, malformed signature, upload size and row overflow",()=>{const bytes=buildCatalogEnrichmentWorkbook({workbookId:"20000000-0000-4000-8000-000000000001",jobId:"30000000-0000-4000-8000-000000000001",exportedAt:"2026-09-13T00:00:00Z",rows:[row()],categories:[],countries:["CN"],includeCosts:false});const encrypted=bytes.slice();for(let offset=0;offset<encrypted.length-10;offset++){if(encrypted[offset]===0x50&&encrypted[offset+1]===0x4b&&encrypted[offset+2]===0x01&&encrypted[offset+3]===0x02){encrypted[offset+8]|=1;break;}}expect(()=>validateCatalogEnrichmentArchive(file(encrypted),encrypted)).toThrow(/เข้ารหัส/);expect(()=>validateCatalogEnrichmentArchive(file(new Uint8Array([1,2,3,4])),new Uint8Array([1,2,3,4]))).toThrow(/signature/);const oversized=new Uint8Array(CATALOG_EXCEL_MAX_BYTES+1);oversized[0]=0x50;oversized[1]=0x4b;expect(()=>validateCatalogEnrichmentArchive(file(oversized),oversized)).toThrow(/10 MB/);expect(()=>buildCatalogEnrichmentWorkbook({workbookId:"20000000-0000-4000-8000-000000000001",jobId:"30000000-0000-4000-8000-000000000001",exportedAt:"2026-09-13T00:00:00Z",rows:Array.from({length:1001},(_,index)=>row(index+1)),categories:[],countries:["CN"],includeCosts:false})).toThrow(/1,000/);});
  it("parses blank, #CLEAR and cost constraints without guessing",()=>{expect(parseOptionalNumber("")).toBeUndefined();expect(parseOptionalNumber("#CLEAR")).toBeNull();expect(parseOptionalNumber("2.5")).toBe(2.5);expect(()=>parseOptionalNumber(0)).toThrow();expect(parseFactoryCost("0")).toBe(0);expect(()=>parseFactoryCost("#CLEAR")).toThrow();expect(safeSpreadsheetText("=SAFE")).toBe("=SAFE");});
  it("counts invalid and conflict summaries once per row",()=>{expect(summarizeEnrichmentStatuses([{detail_status:"INVALID",cost_status:"INVALID"},{detail_status:"CONFLICT",cost_status:"CONFLICT"},{detail_status:"UNCHANGED",cost_status:"UNCHANGED"}])).toEqual({readyDetails:0,readyCosts:0,invalid:1,conflicts:1,unchanged:1,waiting:0});});
  it("uses only a confidential PDF source metadata name and falls back safely",()=>{const jobId="30000000-0000-4000-8000-000000000001";expect(resolveCatalogEnrichmentFilename(jobId,{original_name:"Kids 家具 Catalog.pdf",bucket:"gisp-confidential",visibility:"CONFIDENTIAL",entity_type:"CATALOG_IMPORT",entity_id:jobId})).toBe("catalog-enrichment-Kids 家具 Catalog.xlsx");expect(resolveCatalogEnrichmentFilename(jobId,{original_name:"secret.pdf",bucket:"public",visibility:"PUBLIC",entity_type:"CATALOG_IMPORT",entity_id:jobId})).toBe("catalog-enrichment-pdf-catalog-30000000.xlsx");expect(resolveCatalogEnrichmentFilename(jobId,{original_name:"../../unsafe?.pdf",bucket:"gisp-confidential",visibility:"CONFIDENTIAL",entity_type:"CATALOG_IMPORT",entity_id:jobId})).toBe("catalog-enrichment-unsafe-.xlsx");});
  it("truncates Unicode filenames without splitting emoji or leaving invalid surrogates",()=>{const jobId="30000000-0000-4000-8000-000000000001";const metadata=(original_name:string)=>({original_name,bucket:"gisp-confidential",visibility:"CONFIDENTIAL",entity_type:"CATALOG_IMPORT",entity_id:jobId});const boundary=resolveCatalogEnrichmentFilename(jobId,metadata(`${"a".repeat(99)}😀.pdf`));expect(boundary).toBe(`catalog-enrichment-${"a".repeat(99)}😀.xlsx`);expect(()=>encodeURIComponent(boundary)).not.toThrow();const malformed=resolveCatalogEnrichmentFilename(jobId,metadata(`${"a".repeat(99)}\ud83d.pdf`));expect(malformed).toBe(`catalog-enrichment-${"a".repeat(99)}-.xlsx`);expect(()=>encodeURIComponent(malformed)).not.toThrow();});
});
